package com.flowable.keys.generate

import com.flowable.keys.model.ModelType

/** A model to emit as a constant: its type, key, and (optional) display name. */
data class ModelInfo(val type: ModelType, val key: String, val name: String)

/**
 * Generates a Java class holding every project model key as a `public static final String`,
 * grouped into a nested class per model type (e.g. `FlowableModelKeys.Process.DEMO_P001`), with
 * the model name in Javadoc. Deterministic (sorted, no timestamp) to avoid VCS churn.
 */
object ModelConstantsGenerator {

    fun generate(models: List<ModelInfo>, fqcn: String): String {
        val pkg = fqcn.substringBeforeLast('.', "")
        val className = fqcn.substringAfterLast('.')
        val byType = models.groupBy { it.type }

        val sb = StringBuilder()
        if (pkg.isNotEmpty()) sb.append("package ").append(pkg).append(";\n\n")
        sb.append("/**\n")
        sb.append(" * Flowable model keys for this project.\n")
        sb.append(" *\n")
        sb.append(" * <p>Generated by the Flowable Keys plugin — DO NOT EDIT. Regenerate via\n")
        sb.append(" * Tools &gt; \"Flowable: Generate Model Constants\".\n")
        sb.append(" */\n")
        sb.append("public final class ").append(className).append(" {\n")
        sb.append("    private ").append(className).append("() {\n    }\n")

        for (type in ModelType.entries) {
            val list = byType[type]?.distinctBy { it.key }?.sortedBy { it.key } ?: continue
            if (list.isEmpty()) continue
            val nested = pascal(type)
            sb.append("\n    /** ").append(type.display).append(" models. */\n")
            sb.append("    public static final class ").append(nested).append(" {\n")
            sb.append("        private ").append(nested).append("() {\n        }\n\n")

            val used = HashSet<String>()
            for (model in list) {
                val ident = uniqueIdentifier(identifier(model.key), used)
                if (model.name.isNotBlank() && model.name != model.key) {
                    sb.append("        /** ").append(escapeComment(model.name)).append(" */\n")
                }
                sb.append("        public static final String ").append(ident)
                    .append(" = \"").append(escapeString(model.key)).append("\";\n")
            }
            sb.append("    }\n")
        }

        sb.append("}\n")
        return sb.toString()
    }

    /** DATA_OBJECT → "DataObject", PROCESS → "Process", SECURITY_POLICY → "SecurityPolicy". */
    private fun pascal(type: ModelType): String =
        type.name.split('_').joinToString("") { part ->
            part.lowercase().replaceFirstChar { it.uppercaseChar() }
        }

    /** "DEMO-P001" → "DEMO_P001"; ensures a valid Java identifier. */
    private fun identifier(key: String): String {
        val sb = StringBuilder(key.length)
        for (c in key) sb.append(if (c == '_' || c.isLetterOrDigit()) c else '_')
        var s = sb.toString().uppercase()
        if (s.isEmpty()) s = "KEY"
        if (s[0].isDigit()) s = "_$s"
        return s
    }

    private fun uniqueIdentifier(base: String, used: MutableSet<String>): String {
        var ident = base
        if (ident in used) {
            var n = 2
            while ("${base}_$n" in used) n++
            ident = "${base}_$n"
        }
        used.add(ident)
        return ident
    }

    private fun escapeString(s: String): String =
        s.replace("\\", "\\\\").replace("\"", "\\\"")

    private fun escapeComment(s: String): String =
        s.replace("*/", "* /")
}
