package com.flowable.atlas.script

/**
 * GENERATED — the public method surfaces of the Flowable engine services that script contexts bind
 * (`runtimeService`, `taskService`, …): member name → parameter names. Feeds completion, the
 * member-typo check and quick documentation via [ScriptBindingsCatalog].
 *
 * Source: the local OSS engine checkout `flowable-engine` (8.1.0-SNAPSHOT, extracted 2026-07-30)
 * — `org.flowable.engine.{Runtime,Task,Repository,History,Management,Form,Identity}Service` and
 * `org.flowable.cmmn.api.Cmmn{Runtime,Task,History,Management}Service`. Overloads are merged into
 * the richest signature (the most informative one for the completion popup).
 *
 * Regeneration (repo convention: no build script, same throwaway approach as the golden files):
 * strip comments from each interface source, collect `name(params);` declarations, split params
 * with angle-bracket balance, keep the last token of each parameter as its name, merge overloads
 * by keeping the longest parameter list, and emit the sorted `mapOf` literals below.
 */
object ScriptServiceApis {

    val RUNTIME_SERVICE: Map<String, String> = mapOf(
        "activateProcessInstanceById" to "processInstanceId",
        "addEventListener" to "listenerToAdd, types",
        "addEventRegistryConsumer" to "eventConsumer",
        "addGroupIdentityLink" to "processInstanceId, groupId, identityLinkType",
        "addMultiInstanceExecution" to "activityId, parentExecutionId, executionVariables",
        "addParticipantGroup" to "processInstanceId, groupId",
        "addParticipantUser" to "processInstanceId, userId",
        "addUserIdentityLink" to "processInstanceId, userId, identityLinkType",
        "bulkDeleteProcessInstances" to "processInstanceIds, deleteReason",
        "claimProcessInstance" to "processInstanceId, userId",
        "completeAdhocSubProcess" to "executionId",
        "createActivityInstanceQuery" to "",
        "createChangeActivityStateBuilder" to "",
        "createEventSubscriptionQuery" to "",
        "createExecutionQuery" to "",
        "createNativeActivityInstanceQuery" to "",
        "createNativeExecutionQuery" to "",
        "createNativeProcessInstanceQuery" to "",
        "createNativeVariableInstanceQuery" to "",
        "createProcessInstanceBuilder" to "",
        "createProcessInstanceQuery" to "",
        "createProcessInstanceStartEventSubscriptionBuilder" to "",
        "createProcessInstanceStartEventSubscriptionDeletionBuilder" to "",
        "createProcessInstanceStartEventSubscriptionModificationBuilder" to "",
        "createProcessInstanceUpdateBuilder" to "processInstanceId",
        "createVariableInstanceQuery" to "",
        "deleteGroupIdentityLink" to "processInstanceId, groupId, identityLinkType",
        "deleteMultiInstanceExecution" to "executionId, executionIsCompleted",
        "deleteParticipantGroup" to "processInstanceId, groupId",
        "deleteParticipantUser" to "processInstanceId, userId",
        "deleteProcessInstance" to "processInstanceId, deleteReason",
        "deleteUserIdentityLink" to "processInstanceId, userId, identityLinkType",
        "dispatchEvent" to "event",
        "evaluateConditionalEvents" to "processInstanceId, processVariables",
        "executeActivityInAdhocSubProcess" to "executionId, activityId",
        "getActiveActivityIds" to "executionId",
        "getAdhocSubProcessExecutions" to "processInstanceId",
        "getDataObject" to "executionId, dataObjectName, locale, withLocalizationFallback",
        "getDataObjectLocal" to "executionId, dataObjectName, locale, withLocalizationFallback",
        "getDataObjects" to "executionId, dataObjectNames, locale, withLocalizationFallback",
        "getDataObjectsLocal" to "executionId, dataObjectNames, locale, withLocalizationFallback",
        "getEnabledActivitiesFromAdhocSubProcess" to "executionId",
        "getEntityLinkChildrenForProcessInstance" to "instanceId",
        "getEntityLinkChildrenForTask" to "taskId",
        "getEntityLinkChildrenWithSameRootAsProcessInstance" to "instanceId",
        "getEntityLinkParentsForProcessInstance" to "instanceId",
        "getEntityLinkParentsForTask" to "taskId",
        "getIdentityLinksForProcessInstance" to "instanceId",
        "getProcessInstanceEvents" to "processInstanceId",
        "getStartFormModel" to "processDefinitionId, processInstanceId",
        "getVariable" to "executionId, variableName, variableClass",
        "getVariableInstance" to "executionId, variableName",
        "getVariableInstanceLocal" to "executionId, variableName",
        "getVariableInstances" to "executionId, variableNames",
        "getVariableInstancesByExecutionIds" to "executionIds",
        "getVariableInstancesLocal" to "executionId, variableNames",
        "getVariableLocal" to "executionId, variableName, variableClass",
        "getVariables" to "executionId, variableNames",
        "getVariablesLocal" to "executionId, variableNames",
        "hasVariable" to "executionId, variableName",
        "hasVariableLocal" to "executionId, variableName",
        "messageEventReceived" to "messageName, executionId, processVariables",
        "messageEventReceivedAsync" to "messageName, executionId",
        "removeAssignee" to "processInstanceId",
        "removeEventListener" to "listenerToRemove",
        "removeEventRegistryConsumer" to "eventConsumer",
        "removeOwner" to "processInstanceId",
        "removeVariable" to "executionId, variableName",
        "removeVariableLocal" to "executionId, variableName",
        "removeVariables" to "executionId, variableNames",
        "removeVariablesLocal" to "executionId, variableNames",
        "setAssignee" to "processInstanceId, userId",
        "setOwner" to "processInstanceId, userId",
        "setProcessInstanceDueDate" to "processInstanceId, dueDate",
        "setProcessInstanceName" to "processInstanceId, name",
        "setVariable" to "executionId, variableName, value",
        "setVariableAsync" to "executionId, variableName, value",
        "setVariableLocal" to "executionId, variableName, value",
        "setVariableLocalAsync" to "executionId, variableName, value",
        "setVariables" to "executionId, variables",
        "setVariablesAsync" to "executionId, variables",
        "setVariablesLocal" to "executionId, variables",
        "setVariablesLocalAsync" to "executionId, variables",
        "signalEventReceived" to "signalName, executionId, processVariables",
        "signalEventReceivedAsync" to "signalName, executionId",
        "signalEventReceivedAsyncWithTenantId" to "signalName, tenantId",
        "signalEventReceivedWithTenantId" to "signalName, processVariables, tenantId",
        "startProcessInstanceById" to "processDefinitionId, businessKey, variables",
        "startProcessInstanceByKey" to "processDefinitionKey, businessKey, variables",
        "startProcessInstanceByKeyAndTenantId" to "processDefinitionKey, businessKey, variables, tenantId",
        "startProcessInstanceByMessage" to "messageName, businessKey, processVariables",
        "startProcessInstanceByMessageAndTenantId" to "messageName, businessKey, processVariables, tenantId",
        "startProcessInstanceWithForm" to "processDefinitionId, outcome, variables, processInstanceName",
        "suspendProcessInstanceById" to "processInstanceId",
        "trigger" to "executionId, processVariables, transientVariables",
        "triggerAsync" to "executionId, processVariables",
        "unclaimProcessInstance" to "processInstanceId",
        "updateBusinessKey" to "processInstanceId, businessKey",
        "updateBusinessStatus" to "processInstanceId, businessStatus",
    )

    val TASK_SERVICE: Map<String, String> = mapOf(
        "activateTask" to "taskId, userId",
        "addCandidateGroup" to "taskId, groupId",
        "addCandidateUser" to "taskId, userId",
        "addComment" to "taskId, processInstanceId, type, message",
        "addGroupIdentityLink" to "taskId, groupId, identityLinkType",
        "addUserIdentityLink" to "taskId, userId, identityLinkType",
        "bulkSaveTasks" to "taskList",
        "claim" to "taskId, userId",
        "complete" to "taskId, userId, variables, transientVariables",
        "completeTaskWithForm" to "taskId, formDefinitionId, outcome, userId, variables, transientVariables",
        "createAttachment" to "attachmentType, taskId, processInstanceId, attachmentName, attachmentDescription, content",
        "createNativeTaskQuery" to "",
        "createTaskBuilder" to "",
        "createTaskCompletionBuilder" to "",
        "createTaskQuery" to "",
        "delegateTask" to "taskId, userId",
        "deleteAttachment" to "attachmentId",
        "deleteCandidateGroup" to "taskId, groupId",
        "deleteCandidateUser" to "taskId, userId",
        "deleteComment" to "commentId",
        "deleteComments" to "taskId, processInstanceId",
        "deleteGroupIdentityLink" to "taskId, groupId, identityLinkType",
        "deleteTask" to "taskId, cascade",
        "deleteTasks" to "taskIds, cascade",
        "deleteUserIdentityLink" to "taskId, userId, identityLinkType",
        "getAttachment" to "attachmentId",
        "getAttachmentContent" to "attachmentId",
        "getComment" to "commentId",
        "getCommentsByType" to "type",
        "getDataObject" to "taskId, dataObjectName, locale, withLocalizationFallback",
        "getDataObjects" to "taskId, dataObjectNames, locale, withLocalizationFallback",
        "getEvent" to "eventId",
        "getIdentityLinksForTask" to "taskId",
        "getProcessInstanceAttachments" to "processInstanceId",
        "getProcessInstanceComments" to "processInstanceId, type",
        "getSubTasks" to "parentTaskId",
        "getTaskAttachments" to "taskId",
        "getTaskComments" to "taskId, type",
        "getTaskEvents" to "taskId",
        "getTaskFormModel" to "taskId, ignoreVariables",
        "getVariable" to "taskId, variableName, variableClass",
        "getVariableInstance" to "taskId, variableName",
        "getVariableInstanceLocal" to "taskId, variableName",
        "getVariableInstances" to "taskId, variableNames",
        "getVariableInstancesLocal" to "taskId, variableNames",
        "getVariableInstancesLocalByTaskIds" to "taskIds",
        "getVariableLocal" to "taskId, variableName, variableClass",
        "getVariables" to "taskId, variableNames",
        "getVariablesLocal" to "taskId, variableNames",
        "hasVariable" to "taskId, variableName",
        "hasVariableLocal" to "taskId, variableName",
        "newTask" to "",
        "removeVariable" to "taskId, variableName",
        "removeVariableLocal" to "taskId, variableName",
        "removeVariables" to "taskId, variableNames",
        "removeVariablesLocal" to "taskId, variableNames",
        "resolveTask" to "taskId, variables, transientVariables",
        "saveAttachment" to "attachment",
        "saveComment" to "comment",
        "saveTask" to "task",
        "setAssignee" to "taskId, userId",
        "setDueDate" to "taskId, dueDate",
        "setOwner" to "taskId, userId",
        "setPriority" to "taskId, priority",
        "setVariable" to "taskId, variableName, value",
        "setVariableLocal" to "taskId, variableName, value",
        "setVariables" to "taskId, variables",
        "setVariablesLocal" to "taskId, variables",
        "startProgress" to "taskId, userId",
        "suspendTask" to "taskId, userId",
        "unclaim" to "taskId",
    )

    val REPOSITORY_SERVICE: Map<String, String> = mapOf(
        "activateProcessDefinitionById" to "processDefinitionId, activateProcessInstances, activationDate",
        "activateProcessDefinitionByKey" to "processDefinitionKey, activateProcessInstances, activationDate, tenantId",
        "addCandidateStarterGroup" to "processDefinitionId, groupId",
        "addCandidateStarterUser" to "processDefinitionId, userId",
        "addModelEditorSource" to "modelId, bytes",
        "addModelEditorSourceExtra" to "modelId, bytes",
        "changeDeploymentParentDeploymentId" to "deploymentId, newParentDeploymentId",
        "changeDeploymentTenantId" to "deploymentId, newTenantId, mergeMode",
        "createDeployment" to "",
        "createDeploymentQuery" to "",
        "createModelQuery" to "",
        "createNativeDeploymentQuery" to "",
        "createNativeModelQuery" to "",
        "createNativeProcessDefinitionQuery" to "",
        "createProcessDefinitionQuery" to "",
        "deleteCandidateStarterGroup" to "processDefinitionId, groupId",
        "deleteCandidateStarterUser" to "processDefinitionId, userId",
        "deleteDeployment" to "deploymentId, cascade",
        "deleteModel" to "modelId",
        "getAppResourceModel" to "deploymentId",
        "getAppResourceObject" to "deploymentId",
        "getBpmnModel" to "processDefinitionId",
        "getDecisionsForProcessDefinition" to "processDefinitionId",
        "getDeploymentResourceNames" to "deploymentId",
        "getFormDefinitionsForProcessDefinition" to "processDefinitionId",
        "getIdentityLinksForProcessDefinition" to "processDefinitionId",
        "getModel" to "modelId",
        "getModelEditorSource" to "modelId",
        "getModelEditorSourceExtra" to "modelId",
        "getProcessDefinition" to "processDefinitionId",
        "getProcessDiagram" to "processDefinitionId",
        "getProcessDiagramLayout" to "processDefinitionId",
        "getProcessModel" to "processDefinitionId",
        "getResourceAsStream" to "deploymentId, resourceName",
        "isFlowable5ProcessDefinition" to "processDefinitionId",
        "isProcessDefinitionSuspended" to "processDefinitionId",
        "newModel" to "",
        "saveModel" to "model",
        "setDeploymentCategory" to "deploymentId, category",
        "setDeploymentKey" to "deploymentId, key",
        "setProcessDefinitionCategory" to "processDefinitionId, category",
        "suspendProcessDefinitionById" to "processDefinitionId, suspendProcessInstances, suspensionDate",
        "suspendProcessDefinitionByKey" to "processDefinitionKey, suspendProcessInstances, suspensionDate, tenantId",
        "validateProcess" to "bpmnModel",
    )

    val HISTORY_SERVICE: Map<String, String> = mapOf(
        "bulkDeleteHistoricProcessInstances" to "instanceIds",
        "createHistoricActivityInstanceQuery" to "",
        "createHistoricDetailQuery" to "",
        "createHistoricProcessInstanceQuery" to "",
        "createHistoricTaskInstanceQuery" to "",
        "createHistoricTaskLogEntryBuilder" to "task",
        "createHistoricTaskLogEntryQuery" to "",
        "createHistoricVariableInstanceQuery" to "",
        "createNativeHistoricActivityInstanceQuery" to "",
        "createNativeHistoricDetailQuery" to "",
        "createNativeHistoricProcessInstanceQuery" to "",
        "createNativeHistoricTaskInstanceQuery" to "",
        "createNativeHistoricTaskLogEntryQuery" to "",
        "createNativeHistoricVariableInstanceQuery" to "",
        "createProcessInstanceHistoryLogQuery" to "processInstanceId",
        "deleteHistoricProcessInstance" to "processInstanceId",
        "deleteHistoricTaskInstance" to "taskId",
        "deleteHistoricTaskLogEntry" to "logNumber",
        "deleteRelatedDataOfRemovedHistoricProcessInstances" to "",
        "deleteTaskAndActivityDataOfRemovedHistoricProcessInstances" to "",
        "getHistoricEntityLinkChildrenForProcessInstance" to "processInstanceId",
        "getHistoricEntityLinkChildrenForTask" to "taskId",
        "getHistoricEntityLinkChildrenWithSameRootAsProcessInstance" to "processInstanceId",
        "getHistoricEntityLinkParentsForProcessInstance" to "processInstanceId",
        "getHistoricEntityLinkParentsForTask" to "taskId",
        "getHistoricIdentityLinksForProcessInstance" to "processInstanceId",
        "getHistoricIdentityLinksForTask" to "taskId",
    )

    val MANAGEMENT_SERVICE: Map<String, String> = mapOf(
        "bulkMoveDeadLetterJobs" to "jobIds, retries",
        "bulkMoveDeadLetterJobsToHistoryJobs" to "jobIds, retries",
        "createBatchBuilder" to "",
        "createBatchPartBuilder" to "batch",
        "createBatchPartQuery" to "",
        "createBatchQuery" to "",
        "createChangeTenantIdBuilder" to "fromTenantId, toTenantId",
        "createDeadLetterJobQuery" to "",
        "createExternalWorkerCompletionBuilder" to "externalJobId, workerId",
        "createExternalWorkerJobAcquireBuilder" to "",
        "createExternalWorkerJobFailureBuilder" to "externalJobId, workerId",
        "createExternalWorkerJobQuery" to "",
        "createHistoryJobQuery" to "",
        "createJobQuery" to "",
        "createSuspendedJobQuery" to "",
        "createTablePageQuery" to "",
        "createTimerJobQuery" to "",
        "databaseSchemaUpgrade" to "connection, catalog, schema",
        "deleteBatch" to "batchId",
        "deleteDeadLetterJob" to "jobId",
        "deleteEventLogEntry" to "logNr",
        "deleteExternalWorkerJob" to "jobId",
        "deleteHistoryJob" to "jobId",
        "deleteJob" to "jobId",
        "deleteSuspendedJob" to "jobId",
        "deleteTimerJob" to "jobId",
        "executeCommand" to "config, command",
        "executeCustomSql" to "customSqlExecution",
        "executeHistoryJob" to "historyJobId",
        "executeJob" to "jobId",
        "findBatchPartsByBatchId" to "batchId",
        "findBatchPartsByBatchIdAndStatus" to "batchId, status",
        "findBatchesBySearchKey" to "searchKey",
        "findJobByCorrelationId" to "jobCorrelationId",
        "getAllBatches" to "",
        "getBatchDocument" to "batchId",
        "getBatchPart" to "batchPartId",
        "getBatchPartDocument" to "batchPartId",
        "getBatchSummary" to "batchId",
        "getDeadLetterJobExceptionStacktrace" to "jobId",
        "getEventLogEntries" to "startLogNr, pageSize",
        "getEventLogEntriesByProcessInstanceId" to "processInstanceId",
        "getExternalWorkerJobErrorDetails" to "jobId",
        "getHistoryJobHistoryJson" to "historyJobId",
        "getJobExceptionStacktrace" to "jobId",
        "getLockManager" to "lockName",
        "getProperties" to "",
        "getSuspendedJobExceptionStacktrace" to "jobId",
        "getTableCount" to "",
        "getTableMetaData" to "tableName",
        "getTableName" to "entityClass, includePrefix",
        "getTimerJobExceptionStacktrace" to "jobId",
        "handleHistoryCleanupTimerJob" to "",
        "moveDeadLetterJobToExecutableJob" to "jobId, retries",
        "moveDeadLetterJobToHistoryJob" to "jobId, retries",
        "moveJobToDeadLetterJob" to "jobId",
        "moveSuspendedJobToExecutableJob" to "jobId",
        "moveTimerToExecutableJob" to "jobId",
        "rescheduleTimeCycleJob" to "jobId, timeCycle",
        "rescheduleTimeDateJob" to "jobId, timeDate",
        "rescheduleTimeDurationJob" to "jobId, timeDuration",
        "rescheduleTimerJob" to "jobId, timeDate, timeDuration, timeCycle, endDate, calendarName",
        "setJobRetries" to "jobId, retries",
        "setTimerJobRetries" to "jobId, retries",
        "unacquireAllExternalWorkerJobsForWorker" to "workerId, tenantId",
        "unacquireExternalWorkerJob" to "jobId, workerId",
    )

    val FORM_SERVICE: Map<String, String> = mapOf(
        "getRenderedStartForm" to "processDefinitionId, formEngineName",
        "getRenderedTaskForm" to "taskId, formEngineName",
        "getStartFormData" to "processDefinitionId",
        "getStartFormKey" to "processDefinitionId",
        "getTaskFormData" to "taskId",
        "getTaskFormKey" to "processDefinitionId, taskDefinitionKey",
        "saveFormData" to "taskId, properties",
        "submitStartFormData" to "processDefinitionId, businessKey, properties",
        "submitTaskFormData" to "taskId, properties",
    )

    val IDENTITY_SERVICE: Map<String, String> = mapOf(
        "checkPassword" to "userId, password",
        "createGroupQuery" to "",
        "createMembership" to "userId, groupId",
        "createNativeGroupQuery" to "",
        "createNativeUserQuery" to "",
        "createUserQuery" to "",
        "deleteGroup" to "groupId",
        "deleteMembership" to "userId, groupId",
        "deleteUser" to "userId",
        "deleteUserInfo" to "userId, key",
        "getPotentialStarterGroups" to "processDefinitionId",
        "getPotentialStarterUsers" to "processDefinitionId",
        "getUserInfo" to "userId, key",
        "getUserInfoKeys" to "userId",
        "getUserPicture" to "userId",
        "newGroup" to "groupId",
        "newUser" to "userId",
        "saveGroup" to "group",
        "saveUser" to "user",
        "setAuthenticatedUserId" to "authenticatedUserId",
        "setUserInfo" to "userId, key, value",
        "setUserPicture" to "userId, picture",
        "updateUserPassword" to "user",
    )

    val CMMN_RUNTIME_SERVICE: Map<String, String> = mapOf(
        "addEventListener" to "listenerToAdd, types",
        "addGroupIdentityLink" to "caseInstanceId, groupId, identityLinkType",
        "addUserIdentityLink" to "caseInstanceId, userId, identityLinkType",
        "bulkDeleteCaseInstances" to "caseInstanceId",
        "bulkTerminateCaseInstances" to "caseInstanceId",
        "claimCaseInstance" to "caseInstanceId, userId",
        "completeCaseInstance" to "caseInstanceId",
        "completeGenericEventListenerInstance" to "genericEventListenerInstanceId",
        "completeIntentEventListenerInstance" to "intentEventListenerInstanceId",
        "completeStagePlanItemInstance" to "planItemInstanceId, force",
        "completeUserEventListenerInstance" to "userEventListenerInstanceId",
        "createCaseInstanceBuilder" to "",
        "createCaseInstanceQuery" to "",
        "createCaseInstanceStartEventSubscriptionBuilder" to "",
        "createCaseInstanceStartEventSubscriptionDeletionBuilder" to "",
        "createCaseInstanceStartEventSubscriptionModificationBuilder" to "",
        "createCaseInstanceUpdateBuilder" to "caseInstanceId",
        "createChangePlanItemStateBuilder" to "",
        "createEventSubscriptionQuery" to "",
        "createGenericEventListenerInstanceQuery" to "",
        "createIntentEventListenerInstanceQuery" to "",
        "createMilestoneInstanceQuery" to "",
        "createPlanItemInstanceQuery" to "",
        "createPlanItemInstanceTransitionBuilder" to "planItemInstanceId",
        "createSignalEventListenerInstanceQuery" to "",
        "createUserEventListenerInstanceQuery" to "",
        "createVariableInstanceQuery" to "",
        "deleteCaseInstance" to "caseInstanceId",
        "deleteGroupIdentityLink" to "caseInstanceId, groupId, identityLinkType",
        "deleteUserIdentityLink" to "caseInstanceId, userId, identityLinkType",
        "disablePlanItemInstance" to "planItemInstanceId",
        "dispatchEvent" to "event",
        "enablePlanItemInstance" to "planItemInstanceId",
        "evaluateCriteria" to "caseInstanceId",
        "getEntityLinkChildrenForCaseInstance" to "instanceId",
        "getEntityLinkChildrenWithSameRootAsCaseInstance" to "instanceId",
        "getEntityLinkParentsForCaseInstance" to "instanceId",
        "getIdentityLinksForCaseInstance" to "instanceId",
        "getIdentityLinksForPlanItemInstance" to "instanceId",
        "getLocalVariable" to "planItemInstanceId, variableName",
        "getLocalVariableInstance" to "planItemInstanceId, variableName",
        "getLocalVariableInstances" to "planItemInstanceId",
        "getLocalVariables" to "planItemInstanceId, variableNames",
        "getStageOverview" to "caseInstanceId",
        "getStartFormModel" to "caseDefinitionId, caseInstanceId",
        "getVariable" to "caseInstanceId, variableName",
        "getVariableInstance" to "caseInstanceId, variableName",
        "getVariableInstances" to "caseInstanceId",
        "getVariables" to "caseInstanceId, variableNames",
        "hasLocalVariable" to "planItemInstanceId, variableName",
        "hasVariable" to "caseInstanceId, variableName",
        "removeAssignee" to "caseInstanceId",
        "removeEventListener" to "listenerToRemove",
        "removeLocalVariable" to "planItemInstanceId, variableName",
        "removeLocalVariables" to "planItemInstanceId, variableNames",
        "removeOwner" to "caseInstanceId",
        "removeVariable" to "caseInstanceId, variableName",
        "removeVariables" to "caseInstanceId, variableNames",
        "setAssignee" to "caseInstanceId, userId",
        "setCaseInstanceDueDate" to "caseInstanceId, dueDate",
        "setCaseInstanceName" to "caseInstanceId, caseName",
        "setLocalVariable" to "planItemInstanceId, variableName, variableValue",
        "setLocalVariableAsync" to "planItemInstanceId, variableName, variableValue",
        "setLocalVariables" to "planItemInstanceId, variables",
        "setLocalVariablesAsync" to "planItemInstanceId, variables",
        "setOwner" to "caseInstanceId, userId",
        "setVariable" to "caseInstanceId, variableName, variableValue",
        "setVariableAsync" to "caseInstanceId, variableName, variableValue",
        "setVariables" to "caseInstanceId, variables",
        "setVariablesAsync" to "caseInstanceId, variables",
        "startPlanItemInstance" to "planItemInstanceId",
        "terminateCaseInstance" to "caseInstanceId",
        "terminatePlanItemInstance" to "planItemInstanceId",
        "triggerPlanItemInstance" to "planItemInstanceId",
        "unclaimCaseInstance" to "caseInstanceId",
        "updateBusinessKey" to "caseInstanceId, businessKey",
        "updateBusinessStatus" to "caseInstanceId, businessStatus",
    )

    val CMMN_TASK_SERVICE: Map<String, String> = mapOf(
        "activateTask" to "taskId, userId",
        "addGroupIdentityLink" to "taskId, groupId, identityLinkType",
        "addUserIdentityLink" to "taskId, userId, identityLinkType",
        "bulkSaveTasks" to "taskList",
        "claim" to "taskId, userId",
        "complete" to "taskId, userId, variables, transientVariables",
        "completeTaskWithForm" to "taskId, formDefinitionId, outcome, userId, variables, transientVariables",
        "createTaskBuilder" to "",
        "createTaskCompletionBuilder" to "",
        "createTaskQuery" to "",
        "delegateTask" to "taskId, userId",
        "deleteGroupIdentityLink" to "taskId, groupId, identityLinkType",
        "deleteTask" to "taskId, cascade",
        "deleteTasks" to "taskIds, cascade",
        "deleteUserIdentityLink" to "taskId, userId, identityLinkType",
        "getIdentityLinksForTask" to "taskId",
        "getSubTasks" to "parentTaskId",
        "getTaskFormModel" to "taskId, ignoreVariables",
        "getVariable" to "taskId, variableName, variableClass",
        "getVariableInstance" to "taskId, variableName",
        "getVariableInstanceLocal" to "taskId, variableName",
        "getVariableInstances" to "taskId, variableNames",
        "getVariableInstancesLocal" to "taskId, variableNames",
        "getVariableInstancesLocalByTaskIds" to "taskIds",
        "getVariableLocal" to "taskId, variableName, variableClass",
        "getVariables" to "taskId, variableNames",
        "getVariablesLocal" to "taskId, variableNames",
        "hasVariable" to "taskId, variableName",
        "hasVariableLocal" to "taskId, variableName",
        "newTask" to "",
        "removeVariable" to "taskId, variableName",
        "removeVariableLocal" to "taskId, variableName",
        "removeVariables" to "taskId, variableNames",
        "removeVariablesLocal" to "taskId, variableNames",
        "resolveTask" to "taskId, variables, transientVariables",
        "saveTask" to "task",
        "setAssignee" to "taskId, userId",
        "setDueDate" to "taskId, dueDate",
        "setOwner" to "taskId, userId",
        "setPriority" to "taskId, priority",
        "setVariable" to "taskId, variableName, value",
        "setVariableLocal" to "taskId, variableName, value",
        "setVariables" to "taskId, variables",
        "setVariablesLocal" to "taskId, variables",
        "startProgress" to "taskId, userId",
        "suspendTask" to "taskId, userId",
        "unclaim" to "taskId",
    )

    val CMMN_HISTORY_SERVICE: Map<String, String> = mapOf(
        "bulkDeleteHistoricCaseInstances" to "caseInstanceIds",
        "createCaseReactivationBuilder" to "caseInstanceId",
        "createHistoricCaseInstanceQuery" to "",
        "createHistoricMilestoneInstanceQuery" to "",
        "createHistoricPlanItemInstanceQuery" to "",
        "createHistoricTaskInstanceQuery" to "",
        "createHistoricTaskLogEntryBuilder" to "task",
        "createHistoricTaskLogEntryQuery" to "",
        "createHistoricVariableInstanceQuery" to "",
        "createNativeHistoricTaskLogEntryQuery" to "",
        "deleteHistoricCaseInstance" to "caseInstanceId",
        "deleteHistoricTaskInstance" to "taskId",
        "deleteHistoricTaskLogEntry" to "logNumber",
        "getHistoricEntityLinkChildrenForCaseInstance" to "caseInstanceId",
        "getHistoricEntityLinkChildrenForTask" to "taskId",
        "getHistoricEntityLinkChildrenWithSameRootAsCaseInstance" to "caseInstanceId",
        "getHistoricEntityLinkParentsForCaseInstance" to "caseInstanceId",
        "getHistoricEntityLinkParentsForTask" to "taskId",
        "getHistoricIdentityLinksForCaseInstance" to "caseInstanceId",
        "getHistoricIdentityLinksForPlanItemInstance" to "planItemInstanceId",
        "getHistoricIdentityLinksForTask" to "taskId",
        "getStageOverview" to "caseInstanceId",
    )

    val CMMN_MANAGEMENT_SERVICE: Map<String, String> = mapOf(
        "bulkMoveDeadLetterJobs" to "jobIds, retries",
        "bulkMoveDeadLetterJobsToHistoryJobs" to "jobIds, retries",
        "createBatchBuilder" to "",
        "createBatchPartBuilder" to "batch",
        "createBatchPartQuery" to "",
        "createBatchQuery" to "",
        "createChangeTenantIdBuilder" to "fromTenantId, toTenantId",
        "createCmmnExternalWorkerTransitionBuilder" to "externalJobId, workerId",
        "createDeadLetterJobQuery" to "",
        "createExternalWorkerJobAcquireBuilder" to "",
        "createExternalWorkerJobFailureBuilder" to "externalJobId, workerId",
        "createExternalWorkerJobQuery" to "",
        "createHistoryJobQuery" to "",
        "createJobQuery" to "",
        "createSuspendedJobQuery" to "",
        "createTimerJobQuery" to "",
        "deleteBatch" to "batchId",
        "deleteDeadLetterJob" to "jobId",
        "deleteHistoryJob" to "jobId",
        "deleteJob" to "jobId",
        "deleteSuspendedJob" to "jobId",
        "deleteTimerJob" to "jobId",
        "executeHistoryJob" to "historyJobId",
        "executeJob" to "jobId",
        "getDeadLetterJobExceptionStacktrace" to "jobId",
        "getExternalWorkerJobErrorDetails" to "jobId",
        "getHistoryJobHistoryJson" to "historyJobId",
        "getJobExceptionStacktrace" to "jobId",
        "getLockManager" to "lockName",
        "getSuspendedJobExceptionStacktrace" to "jobId",
        "getTableCounts" to "",
        "getTableNames" to "",
        "getTimerJobExceptionStacktrace" to "jobId",
        "handleHistoryCleanupTimerJob" to "",
        "moveDeadLetterJobToExecutableJob" to "jobId, retries",
        "moveDeadLetterJobToHistoryJob" to "jobId, retries",
        "moveJobToDeadLetterJob" to "jobId",
        "moveSuspendedJobToExecutableJob" to "jobId",
        "moveTimerToExecutableJob" to "jobId",
        "rescheduleTimeDateJob" to "jobId, timeDate",
        "rescheduleTimeDateValueJob" to "jobId, timeDateValue",
        "rescheduleTimerEventListenerInstanceWithDate" to "eventListenerInstanceId, timeDate",
        "rescheduleTimerEventListenerInstanceWithDateValue" to "eventListenerInstanceId, timeDateValue",
        "setJobRetries" to "jobId, retries",
        "setTimerJobRetries" to "jobId, retries",
        "unacquireAllExternalWorkerJobsForWorker" to "workerId, tenantId",
        "unacquireExternalWorkerJob" to "jobId, workerId",
    )}
