package com.flowable.keys.intention

import com.flowable.keys.index.DataField

/**
 * Deterministic String → Java-source generator for a typed POJO mapping a Flowable data object's
 * `fieldMappings`, so a `DataObjectInstanceQuery` result can be mapped onto a bean instead of the
 * generic `DataObjectInstanceVariableContainer`. The bean also carries a static `fromContainer(...)`
 * mapper that reads each field off the container with the matching typed accessor. Pure (no PSI) so
 * it is unit-testable.
 */
object DataObjectBeanGenerator {

    private const val CONTAINER_FQN = "com.flowable.dataobject.api.runtime.DataObjectInstanceVariableContainer"
    private const val CONTAINER = "DataObjectInstanceVariableContainer"

    private data class Prop(val property: String, val field: String, val type: String)

    fun generate(packageName: String?, className: String, dataObjectKey: String, fields: List<DataField>): String {
        val props = fields.mapNotNull { f ->
            val ident = identifier(f.name) ?: return@mapNotNull null
            Prop(f.name, ident, javaType(f.type))
        }.distinctBy { it.field }

        return buildString {
            if (!packageName.isNullOrBlank()) append("package ").append(packageName).append(";\n\n")
            append("import ").append(CONTAINER_FQN).append(";\n\n")
            append("/**\n")
            append(" * Bean mapping the fields of Flowable data object '").append(dataObjectKey).append("'.\n")
            append(" * Generated by the Flowable Keys plugin — adjust as needed.\n")
            append(" */\n")
            append("public class ").append(className).append(" {\n\n")

            for (p in props) append("    private ").append(p.type).append(' ').append(p.field).append(";\n")
            if (props.isNotEmpty()) append('\n')

            // Mapper: DataObjectInstanceVariableContainer → this bean.
            append("    /** Maps a Flowable data-object query result onto this bean. */\n")
            append("    public static ").append(className).append(" fromContainer(").append(CONTAINER).append(" container) {\n")
            append("        ").append(className).append(" bean = new ").append(className).append("();\n")
            for (p in props) {
                append("        bean.set").append(p.field.replaceFirstChar { it.uppercaseChar() })
                    .append('(').append(accessor(p)).append(");\n")
            }
            append("        return bean;\n    }\n\n")

            for (p in props) {
                val cap = p.field.replaceFirstChar { it.uppercaseChar() }
                append("    public ").append(p.type).append(" get").append(cap).append("() {\n")
                append("        return ").append(p.field).append(";\n    }\n\n")
                append("    public void set").append(cap).append('(').append(p.type).append(' ').append(p.field).append(") {\n")
                append("        this.").append(p.field).append(" = ").append(p.field).append(";\n    }\n\n")
            }

            // Fluent builder.
            append("    public static Builder builder() {\n        return new Builder();\n    }\n\n")
            append("    public static final class Builder {\n")
            append("        private final ").append(className).append(" bean = new ").append(className).append("();\n\n")
            for (p in props) {
                append("        public Builder ").append(p.field).append('(').append(p.type).append(' ').append(p.field).append(") {\n")
                append("            bean.").append(p.field).append(" = ").append(p.field).append(";\n")
                append("            return this;\n        }\n\n")
            }
            append("        public ").append(className).append(" build() {\n            return bean;\n        }\n    }\n")

            append("}\n")
        }
    }

    /** The container accessor expression that reads [Prop.property] with the type-matching getter. */
    private fun accessor(p: Prop): String {
        val key = "\"" + p.property.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
        return when (p.type) {
            "String" -> "container.getString($key)"
            "Integer" -> "container.getInteger($key)"
            "Long" -> "container.getLong($key)"
            "Double" -> "container.getDouble($key)"
            "Boolean" -> "container.getBoolean($key)"
            "java.util.Date" -> "container.getDate($key)"
            "java.time.LocalDate" -> "container.getLocalDate($key)"
            else -> "container.getValue($key, Object.class)"
        }
    }

    /** A valid PascalCase Java class name derived from the model name (falling back to the key). */
    fun classNameFor(name: String?, key: String): String {
        val source = name?.takeIf { it.isNotBlank() } ?: key
        val camel = source.split(Regex("[^A-Za-z0-9]+"))
            .filter { it.isNotBlank() }
            .joinToString("") { it.replaceFirstChar { c -> c.uppercaseChar() } }
        val cleaned = camel.ifBlank { "DataObjectBean" }
        return if (cleaned.first().isDigit()) "M$cleaned" else cleaned
    }

    /** Map a Flowable logical field type to a Java type. */
    fun javaType(logicalType: String?): String = when (logicalType?.uppercase()) {
        "STRING" -> "String"
        "INT", "INTEGER" -> "Integer"
        "LONG" -> "Long"
        "DOUBLE" -> "Double"
        "BOOLEAN", "BOOL" -> "Boolean"
        "DATE" -> "java.util.Date"
        "LOCAL-DATE", "LOCALDATE" -> "java.time.LocalDate"
        "JSON" -> "String"
        else -> "Object" // DATA-OBJECT relations and unknown types
    }

    /** A valid Java field identifier from a logical field name, or null if nothing usable remains. */
    private fun identifier(raw: String?): String? {
        val cleaned = (raw ?: "").filterIndexed { i, c -> c.isLetterOrDigit() || c == '_' || (i > 0 && c == '$') }
        if (cleaned.isBlank()) return null
        return if (cleaned.first().isDigit()) "_$cleaned" else cleaned
    }
}
