#!/usr/bin/env node
// Regenerates the embedded Geist @font-face blocks at the end of
// core/src/main/resources/frontend/explorer.css.
//
// The explorer HTML is fully offline, so the font travels inside the CSS as
// base64 woff2 data URIs. To keep the payload small each weight is subset to
// Latin + Latin-1 + Latin Extended-A + common punctuation; anything outside
// that range (UI glyphs like ▸ ◐ ⌕) falls back to the system font stack.
//
// Usage:  npm install subset-font --registry=https://registry.npmjs.org/
//         node scripts/embed-geist.mjs
//         (the registry override matters: the Flowable default registry does not mirror subset-font)
// Fonts:  ../flowable-platform/frontend/packages/flowable-api/styles/fonts/geist
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import subsetFont from 'subset-font';

const here = path.dirname(fileURLToPath(import.meta.url));
const fontDir = path.resolve(here, '../../flowable-platform/frontend/packages/flowable-api/styles/fonts/geist');
const cssFile = path.resolve(here, '../core/src/main/resources/frontend/explorer.css');

// weight ranges: bold text (700) intentionally resolves to SemiBold — the Hub
// aesthetic never goes heavier than 600.
const faces = [
  { file: 'Geist-Regular.ttf',  range: '100 499' },
  { file: 'Geist-Medium.ttf',   range: '500 599' },
  { file: 'Geist-SemiBold.ttf', range: '600 900' },
];

let text = '';
for (const [a, b] of [[0x20, 0x7e], [0xa0, 0xff], [0x100, 0x17f], [0x2013, 0x2026]]) {
  for (let c = a; c <= b; c++) text += String.fromCharCode(c);
}
text += '€‹›→·';

const BEGIN = '/* __GEIST_EMBED_BEGIN__ (generated by scripts/embed-geist.mjs — do not edit) */';
const END = '/* __GEIST_EMBED_END__ */';

const blocks = [BEGIN];
for (const f of faces) {
  const ttf = fs.readFileSync(path.join(fontDir, f.file));
  const woff2 = await subsetFont(ttf, text, { targetFormat: 'woff2' });
  console.log(`${f.file}: ${ttf.length} -> ${woff2.length} bytes (woff2 subset)`);
  blocks.push(
    `@font-face{font-family:"Geist";font-style:normal;font-weight:${f.range};font-display:swap;` +
    `src:url(data:font/woff2;base64,${woff2.toString('base64')}) format("woff2")}`,
  );
}
blocks.push(END);
const embed = blocks.join('\n');

let css = fs.readFileSync(cssFile, 'utf8');
if (css.includes(BEGIN)) {
  css = css.replace(new RegExp(`${BEGIN.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`), embed);
} else {
  css = css.trimEnd() + '\n\n' + embed + '\n';
}
fs.writeFileSync(cssFile, css);
console.log(`updated ${cssFile}`);
