package com.flowable.atlas.generate

import com.flowable.atlas.model.ModelType

/** A model to emit as a constant: its type, key, and (optional) display name. */
data class ModelInfo(val type: ModelType, val key: String, val name: String)

/** How the generated identifier is derived. */
enum class ConstantNaming { KEY, NAME, NAME_AND_KEY }

/** Whether each model-type group is a class of String constants or an enum. */
enum class ConstantFormat { CLASS, ENUM }

/**
 * Generates a Java class holding every project model key, grouped into a nested member per model
 * type. Two switchable dimensions:
 *  - [ConstantNaming]: identifier from the KEY (`P_0001`), the NAME (`ORDER_FULFILMENT`), or
 *    NAME_AND_KEY (`ORDER_FULFILMENT_P_0001` — readable and unique/stable). The name part is capped
 *    at [MAX_NAME_CHARS] on a word boundary so long names don't explode the identifier.
 *  - [ConstantFormat]: a class of `public static final String` constants, or an `enum` carrying
 *    `key()` + `displayName()`.
 * Deterministic (sorted, no timestamp) to avoid VCS churn.
 */
object ModelConstantsGenerator {

    private const val MAX_NAME_CHARS = 40

    fun generate(
        models: List<ModelInfo>,
        fqcn: String,
        naming: ConstantNaming = ConstantNaming.NAME_AND_KEY,
        format: ConstantFormat = ConstantFormat.CLASS,
    ): String {
        val pkg = fqcn.substringBeforeLast('.', "")
        val className = fqcn.substringAfterLast('.')
        val byType = models.groupBy { it.type }

        val sb = StringBuilder()
        if (pkg.isNotEmpty()) sb.append("package ").append(pkg).append(";\n\n")
        sb.append("/**\n")
        sb.append(" * Flowable model keys for this project.\n")
        sb.append(" *\n")
        sb.append(" * <p>Generated by the Flowable Atlas plugin — DO NOT EDIT. Regenerate via\n")
        sb.append(" * Tools &gt; Flowable Atlas &gt; \"Generate Model Constants…\".\n")
        sb.append(" */\n")
        sb.append("public final class ").append(className).append(" {\n")
        sb.append("    private ").append(className).append("() {\n    }\n")

        for (type in ModelType.entries) {
            val list = byType[type]?.distinctBy { it.key }?.sortedBy { it.key } ?: continue
            if (list.isEmpty()) continue
            val nested = pascal(type)
            sb.append("\n    /** ").append(type.display).append(" models. */\n")
            when (format) {
                ConstantFormat.CLASS -> appendClass(sb, nested, list, naming)
                ConstantFormat.ENUM -> appendEnum(sb, nested, list, naming)
            }
        }

        sb.append("}\n")
        return sb.toString()
    }

    private fun appendClass(sb: StringBuilder, nested: String, list: List<ModelInfo>, naming: ConstantNaming) {
        sb.append("    public static final class ").append(nested).append(" {\n")
        sb.append("        private ").append(nested).append("() {\n        }\n\n")
        val used = HashSet<String>()
        for (model in list) {
            val ident = uniqueIdentifier(constantName(model, naming), used)
            if (model.name.isNotBlank() && model.name != model.key) {
                sb.append("        /** ").append(escapeComment(model.name)).append(" */\n")
            }
            sb.append("        public static final String ").append(ident)
                .append(" = \"").append(escapeString(model.key)).append("\";\n")
        }
        sb.append("    }\n")
    }

    private fun appendEnum(sb: StringBuilder, nested: String, list: List<ModelInfo>, naming: ConstantNaming) {
        sb.append("    public enum ").append(nested).append(" {\n")
        val used = HashSet<String>()
        val entries = list.map { model ->
            val ident = uniqueIdentifier(constantName(model, naming), used)
            Triple(ident, model.key, model.name)
        }
        entries.forEachIndexed { i, (ident, key, name) ->
            val terminator = if (i == entries.lastIndex) ";" else ","
            if (name.isNotBlank() && name != key) sb.append("        /** ").append(escapeComment(name)).append(" */\n")
            sb.append("        ").append(ident).append("(\"").append(escapeString(key)).append("\", \"")
                .append(escapeString(name)).append("\")").append(terminator).append("\n")
        }
        sb.append("\n        private final String key;\n")
        sb.append("        private final String displayName;\n\n")
        sb.append("        ").append(nested).append("(String key, String displayName) {\n")
        sb.append("            this.key = key;\n            this.displayName = displayName;\n        }\n\n")
        sb.append("        public String key() {\n            return key;\n        }\n\n")
        sb.append("        public String displayName() {\n            return displayName;\n        }\n")
        sb.append("    }\n")
    }

    /** The identifier for a model under the chosen [naming] scheme. */
    private fun constantName(model: ModelInfo, naming: ConstantNaming): String = when (naming) {
        ConstantNaming.KEY -> identifier(model.key)
        ConstantNaming.NAME -> nameIdentifier(model.name).ifEmpty { identifier(model.key) }
        ConstantNaming.NAME_AND_KEY -> {
            val namePart = nameIdentifier(model.name)
            if (namePart.isEmpty() || model.name == model.key) identifier(model.key)
            else namePart + "_" + identifier(model.key)
        }
    }

    /** DATA_OBJECT → "DataObject", PROCESS → "Process", SECURITY_POLICY → "SecurityPolicy". */
    private fun pascal(type: ModelType): String =
        type.name.split('_').joinToString("") { part ->
            part.lowercase().replaceFirstChar { it.uppercaseChar() }
        }

    /** "DEMO-P001" → "DEMO_P001"; ensures a valid Java identifier. */
    private fun identifier(key: String): String {
        val sb = StringBuilder(key.length)
        for (c in key) sb.append(if (c == '_' || c.isLetterOrDigit()) c else '_')
        var s = sb.toString().uppercase()
        if (s.isEmpty()) s = "KEY"
        if (s[0].isDigit()) s = "_$s"
        return s
    }

    /**
     * UPPER_SNAKE_CASE identifier from a model name, capped at [MAX_NAME_CHARS] on a word boundary
     * (always keeps at least the first word). Empty if the name yields no usable word.
     */
    private fun nameIdentifier(name: String): String {
        val words = name.split(Regex("[^A-Za-z0-9]+")).filter { it.isNotBlank() }.map { it.uppercase() }
        if (words.isEmpty()) return ""
        val sb = StringBuilder()
        for (w in words) {
            if (sb.isNotEmpty() && sb.length + 1 + w.length > MAX_NAME_CHARS) break
            if (sb.isNotEmpty()) sb.append('_')
            sb.append(w)
        }
        var s = sb.toString()
        if (s.isNotEmpty() && s[0].isDigit()) s = "_$s"
        return s
    }

    private fun uniqueIdentifier(base: String, used: MutableSet<String>): String {
        var ident = base
        if (ident in used) {
            var n = 2
            while ("${base}_$n" in used) n++
            ident = "${base}_$n"
        }
        used.add(ident)
        return ident
    }

    private fun escapeString(s: String): String =
        s.replace("\\", "\\\\").replace("\"", "\\\"")

    private fun escapeComment(s: String): String =
        s.replace("*/", "* /")
}
