package com.flowable.atlas.render

import com.flowable.atlas.model.MiniJson
import java.io.File

/**
 * CLAUDE.md generator: a generic Flowable primer + this project's discovered facts.
 *
 * Port of `flowable_atlas.py` `claude_render(result, root)` (+ inner helpers `folder`/`keypat`/
 * `_first`/`_cls`). The generic §1–§3 / §5 blocks live inline as the `CLAUDE_PLATFORM` / `CLAUDE_RULES`
 * constants exactly as Python defines them (Python does NOT read `CLAUDE.template.md` — that file is a
 * standalone doc template, unrelated to this generator). No golden exists; parity is checked by diffing
 * against the real Python output in the smoke test.
 */
object ClaudeRenderer {

    @Suppress("UNCHECKED_CAST")
    fun render(result: Map<String, Any?>, root: File): String {
        val name = splitextName(File(root.path.trimEnd('/')).absoluteFile.name).ifEmpty { "project" }
        val s = result["stats"] as Map<String, Any?>
        val nodes = (result["graph"] as Map<String, Any?>)["nodes"] as List<Map<String, Any?>>
        val byType = LinkedHashMap<String, MutableList<Map<String, Any?>>>()
        for (n in nodes) byType.getOrPut(n["type"] as String) { ArrayList() }.add(n)
        fun bt(t: String): List<Map<String, Any?>> = byType[t] ?: emptyList()
        val MODEL = setOf("app", "process", "case", "decision", "form", "page", "dataObject", "dataDictionary",
            "service", "agent", "channel", "event", "action", "query", "template", "sequence",
            "securityPolicy", "variableExtractor", "masterData", "document", "dashboardComponent")

        val digits = Regex("\\d+")

        fun folder(f: Any?): String {
            val fs = (if (truthy(f)) f.toString() else "").substringBefore("!")
            return if (fs.contains("/")) fs.substringBeforeLast("/") else "."
        }

        fun keypat(t: String): String? {
            val keys = bt(t).mapNotNull { val k = it["key"]; if (truthy(k)) k as String else null }
            if (keys.isEmpty()) return null
            val counts = LinkedHashMap<String, Int>()
            for (k in keys) { val p = k.replace(digits, "#"); counts[p] = (counts[p] ?: 0) + 1 }
            val pat = counts.entries.maxByOrNull { it.value }!!.key
            val example = keys.firstOrNull { it.replace(digits, "#") == pat } ?: keys[0]
            return "`$pat` (e.g. `$example`)"
        }

        val L = ArrayList<String>()
        L.add("# CLAUDE.md — `$name` (Flowable solution project)\n")
        L.add("_Auto-generated by Flowable Atlas: a generic Flowable primer + this project's discovered map. " +
                "Regenerate with `atlas <project-dir>`. Edit freely — re-running overwrites only the Atlas copy._\n")

        // §0 — start here, pointing at the actual artifact filenames
        L.add("## 0. Understand this project — start here\n")
        L.add("Don't guess — build the picture in order:")
        L.add("1. Read **`$name.summary.md`** — apps, inventory, entry points, integrations, hotspots.")
        L.add("2. Query **`$name.graph.json`** for specific questions (what calls X, who uses variable Y, " +
                "which controller serves form Z) — relationships are bidirectional (model↔code).")
        L.add("3. Open **`$name.explorer.html`** for the clickable view.")
        L.add("4. Read the actual source to verify, then implement.\n")

        L.add(CLAUDE_PLATFORM)

        // §4 — discovered facts
        L.add("## 4. This project (auto-discovered by Atlas)\n")
        L.add("- **Scale:** ${s["models"]} model files · ${s["java"]} Java files · " +
                "${s["nodes"] ?: 0} graph nodes · ${s["edges"] ?: 0} relationships · ${s["groups"] ?: 0} user groups.")
        if (bt("app").isNotEmpty()) {
            L.add("- **Apps:** " + bt("app").joinToString(", ") { "${it["label"]} (`${it["key"]}`)" })
        }
        val order = listOf("process", "case", "decision", "form", "page", "dataObject", "service", "agent",
            "channel", "event", "action", "query", "template", "sequence", "variableExtractor")
        val inv = order.filter { bt(it).isNotEmpty() }.joinToString(" · ") { "${bt(it).size} $it" }
        if (inv.isNotEmpty()) L.add("- **Models:** " + inv)
        val jr = LinkedHashMap<String, Int>()
        for (n in bt("java")) {
            for (r in ((n["data"] as Map<String, Any?>)["roles"] as? List<String> ?: emptyList())) {
                jr[r] = (jr[r] ?: 0) + 1
            }
        }
        if (jr.isNotEmpty()) {
            L.add("- **Java by role:** " + jr.entries.sortedByDescending { it.value }
                .joinToString(" · ") { "${it.value} ${it.key}" })
        }
        val mf = LinkedHashMap<String, Int>()
        for (n in nodes) if (n["type"] in MODEL && truthy(n["file"])) {
            val d = folder(n["file"]); mf[d] = (mf[d] ?: 0) + 1
        }
        val jf = LinkedHashMap<String, Int>()
        for (n in bt("java")) if (truthy(n["file"])) { val d = folder(n["file"]); jf[d] = (jf[d] ?: 0) + 1 }
        if (mf.isNotEmpty()) {
            L.add("- **Models live in:** " + mf.entries.sortedByDescending { it.value }.take(5)
                .joinToString(", ") { "`${it.key}/` (${it.value})" })
        }
        if (jf.isNotEmpty()) {
            L.add("- **Java lives in:** " + jf.entries.sortedByDescending { it.value }.take(5)
                .joinToString(", ") { "`${it.key}/` (${it.value})" })
        }
        val convs = listOf("process", "case", "form", "decision", "service", "dataObject", "query")
            .mapNotNull { t -> keypat(t)?.let { "$t $it" } }
        if (convs.isNotEmpty()) L.add("- **Key conventions:** " + convs.joinToString("; "))
        val access = result["access"] as? List<Map<String, Any?>> ?: emptyList()
        val starts = access.filter { it["action"] == "start" }.map { it["model"] as String }.distinct().sorted()
        if (starts.isNotEmpty()) {
            L.add("- **Startable entry points:** ${starts.size} processes/cases — see `$name.summary.md`.")
        }

        // build / version detection
        if (root.isDirectory) {
            fun fileExists(vararg p: String): Boolean = File(root, p.joinToString("/")).exists()
            val b = ArrayList<String>()
            if (fileExists("mvnw") || fileExists("pom.xml")) {
                b.add("Maven — `./mvnw clean install -DskipTests -T 1C`; tests `./mvnw test -pl <module> -am -Dtest=Class` " +
                        "(use `-am` on scoped builds)")
            }
            if (fileExists("gradlew") || fileExists("build.gradle")) b.add("Gradle — `./gradlew build`")
            for (fe in listOf("frontend", "ui", "web", "src/main/frontend")) {
                if (fileExists(fe, "package.json")) { b.add("Frontend — `cd $fe && yarn install && yarn build`"); break }
            }
            if (b.isNotEmpty()) L.add("- **Build/test:** " + b.joinToString("; "))
            // run & verify loop (detect frontend start script + a backend app module)
            val run = ArrayList<String>()
            val feDir = listOf("frontend", "ui", "web", "src/main/frontend").firstOrNull { fileExists(it, "package.json") }
            if (feDir != null) {
                try {
                    val pkg = MiniJson.parse(File(root, "$feDir/package.json").readText()) as Map<String, Any?>
                    val scripts = (pkg["scripts"] as? Map<String, Any?>) ?: emptyMap()
                    val cand = scripts.keys.filter { it.startsWith("start") }
                        .ifEmpty { scripts.keys.filter { it == "dev" || it == "serve" } }
                    if (cand.isNotEmpty()) run.add("frontend `cd $feDir && yarn ${cand.sorted().first()}`")
                } catch (_: Exception) { }
            }
            val appmod = try {
                (root.listFiles()?.map { it.name }?.sorted() ?: emptyList()).firstOrNull { d ->
                    File(root, d).isDirectory &&
                            (d.endsWith("-app") || d.endsWith("-work") || d.endsWith("-workflow") || d.endsWith("-runtime"))
                }
            } catch (_: Exception) { null }
            if (appmod != null) run.add("backend = Spring Boot app in `$appmod/`")
            L.add("- **Run & verify:** " + (if (run.isNotEmpty()) run.joinToString("; ") + "; " else "") +
                    "the app auto-deploys its bundled models on startup — exercise the change in the Work UI, " +
                    "or cover backend logic with a test.")
            var ver: String? = null
            try {
                if (fileExists("pom.xml")) {
                    val pom = File(root, "pom.xml").readText()
                    val m = Regex("<flowable(?:[.-]engine|[.-]bom|[.-]platform)?\\.version>\\s*([0-9][^<\\s]+)").find(pom)
                        ?: Regex("(?:com|org)\\.flowable\\b[^<]*</groupId>\\s*<artifactId>[^<]*</artifactId>" +
                                "\\s*<version>\\s*([0-9][^<\\s]+)", RegexOption.DOT_MATCHES_ALL).find(pom)
                    val cand = m?.groupValues?.get(1)?.trim()
                    ver = if (cand != null && cand.isNotEmpty() && Regex("^[6-9]\\.").containsMatchIn(cand)) cand else null
                }
            } catch (_: Exception) { ver = null }
            L.add("- **Flowable version:** " + (if (!ver.isNullOrEmpty()) ver else "see pom.xml / dependencies (not auto-detected)"))
        }

        // Concrete wiring examples, auto-picked from the resolved graph — mirror these for new code.
        val rr = result["resolvedRefs"] as? List<Map<String, Any?>> ?: emptyList()
        fun first(pred: (Map<String, Any?>) -> Boolean): Map<String, Any?>? = rr.firstOrNull(pred)
        fun cls(fqn: Any?): String = if (truthy(fqn)) (fqn as String).substringAfterLast(".") else pystr(fqn)

        val examples = ArrayList<String>()
        val d = first { it["rel"] == "serviceTask-delegate" && truthy(it["targetFqn"]) }
        if (d != null) {
            examples.add("- **Delegate:** process `${d["from"]}` → `\${${d["value"]}}` → " +
                    "`${cls(d["targetFqn"])}` (`${d["targetFqn"]}`)")
        }
        val ls = first {
            val rel = it["rel"] as String
            (rel.startsWith("taskListener") || rel.startsWith("executionListener") ||
                    rel.startsWith("planItemLifecycleListener")) && truthy(it["targetFqn"])
        }
        if (ls != null) examples.add("- **Listener:** `${ls["from"]}` → `${cls(ls["targetFqn"])}` (${ls["rel"]})")
        val cm = first { (it["rel"] as String).startsWith("calls ") && truthy(it["targetFqn"]) }
        if (cm != null) {
            val method = (cm["rel"] as String).substring(6).trimEnd('(', ')')
            examples.add("- **Expression → method:** `${cm["from"]}` → `\${${cm["value"]}.$method(…)}` → " +
                    "`${cls(cm["targetFqn"])}`")
        }
        val edges = (result["graph"] as Map<String, Any?>)["edges"] as List<Map<String, Any?>>
        val bote = edges.firstOrNull { it["rel"] == "bot" && (it["t"] as String).startsWith("java:") }
        if (bote != null) {
            examples.add("- **Bot:** action `${(bote["s"] as String).substringAfter(":")}` → " +
                    "`${(bote["t"] as String).substringAfterLast(".")}` (BotService)")
        }
        val rc = (result["restCalls"] as? List<Map<String, Any?>> ?: emptyList())
            .firstOrNull { truthy(it["matches"]) && it["url"] is String }
        if (rc != null) {
            val u = rc["url"] as String
            val url = if (u.length > 60) u.take(60) + "…" else u
            val matches = rc["matches"] as List<*>
            examples.add("- **Form → REST:** `${rc["source"]}` calls `${rc["method"]} $url` → ${matches[0]}")
        }
        if (examples.isNotEmpty()) {
            L.add("\n**Wiring examples in this project — mirror these for new code:**")
            L.addAll(examples)
        }

        L.add("")
        L.add("> `<!-- Add house rules: code style, where business logic goes, what NOT to touch, " +
                "how this app is deployed/published to Work. -->`\n")

        L.add(CLAUDE_RULES)
        return L.joinToString("\n")
    }

    /** Mirror of `os.path.splitext(base)[0]`: strip a trailing extension (last dot preceded by a non-dot). */
    private fun splitextName(base: String): String {
        val dot = base.lastIndexOf('.')
        if (dot < 0) return base
        for (i in 0 until dot) if (base[i] != '.') return base.substring(0, dot)
        return base
    }

    /** Python truthiness for `.get(...) or …` / `if x:` idioms (None/""/0/empty → false). */
    private fun truthy(v: Any?): Boolean = when (v) {
        null -> false
        is Boolean -> v
        is String -> v.isNotEmpty()
        is Number -> v.toDouble() != 0.0
        is Collection<*> -> v.isNotEmpty()
        is Map<*, *> -> v.isNotEmpty()
        else -> true
    }

    private fun pystr(v: Any?): String = v?.toString() ?: "None"

    private val CLAUDE_PLATFORM = """## 1. What Flowable is (the mental model an LLM usually gets wrong)

Flowable is a Java process-automation platform. A solution project is custom Java + models that run
**on top of** the Flowable engines — you extend a platform, you don't build from scratch.

- **Work** = the **runtime *and* the end-user React frontend** (executes definitions, renders forms,
  hosts tasks/cases). Custom Java + REST controllers run here. **Design** = the visual modeler.
  (Control/Hub = admin consoles.) Engines: BPMN (processes), CMMN (cases), DMN (decisions), Form, IDM.

**Models vs Definitions (the key concept):** models are mutable design-time JSON; when deployed they
become **immutable, versioned Definitions** (stored in the DB's `ACT_*` tables — rarely touched
directly; use the engine services/APIs). Everything is referenced by **key** (process/case/form/decision
key) — cross-references between models, from Java, and from the frontend are all by key.

**In a solution project, models are authored in Design and *exported into this repo*** — the `.app`/`.zip`
and model files under `src/main/resources` are **exported build artifacts**, not the editing surface.
The Java app is built **together with** the bundled model and deploys it to Work on startup. The canonical
place to *change* a model is Flowable **Design**, then re-export.

## 2. How custom code attaches to models (extension points)

- **Service tasks / JavaDelegate** — `flowable:class="com.acme.X"` or `flowable:delegateExpression="${'$'}{bean}"` (a Spring `@Component`/`@Service`).
- **Expressions** — `${'$'}{bean.method(args)}` (backend, JUEL) in conditions/listeners/fields; `{{ ... }}` (frontend) in forms/pages.
- **Listeners** — Execution/Task/PlanItemLifecycle/CaseInstanceLifecycle/FlowableEventListener.
- **REST controllers** — `@RestController` endpoints the Work frontend (forms, data tables, buttons) calls.
- **Bots** (`BotService`) — invoked by **Actions** (`.action` models, via `botKey`).
- **Service-registry data objects** — `.data` backed by a `.service` (REST/DB); DB-backed map to **Liquibase** tables.
- **Forms** — bind fields to **variables**; outcomes drive flow; can call REST for options/data tables.
- **Queries** (`.query`) — index queries (tasks/case-instances/…), often gated by **user group**.
- **Variables** — set in Java (`execution.setVariable(...)`), init-var mappings, in/out params, sequences; read in expressions.
- **Access** — candidate (starter) groups, task candidate groups/assignees, app/page permissions, security policies.

## 3. How models, code and deployment fit together (important — easy to get wrong)

- **Models are authored in Design, not here.** A modeler builds BPMN/CMMN/forms/etc. in Flowable
  **Design**, then **exports/publishes the app into this repo**. Treat the repo's model files as
  exported artifacts — don't hand-edit the deployed `.zip` as if you own it; model changes normally
  go back through Design and are re-exported.
- **Build = your Java + the bundled model, together.** The Maven build packages the custom Java **and**
  the exported app; on deploy/startup the app **auto-deploys** its definitions to Work.
- **Deploy via the built artifact, environment by environment** (dev → test → **prod**, via CI/CD). You
  typically do **not** publish from Design straight to Production — Design-publish is a dev-time
  convenience; production receives the built-and-deployed app.

**Your lane as an agent:** implement/adjust the **custom Java** (delegates, beans, listeners, REST
controllers, bots) to match the models, and **read** the models to understand the wiring. If a feature
needs a model change (new task/form/variable/decision), **say so explicitly and describe it** — it's
made in Design and re-exported, unless this project's convention is to edit the model files directly
(check existing commits/patterns first). Always mirror an existing similar case — find it via Atlas.
"""

    private val CLAUDE_RULES = """## 5. Rules for the agent

- **Understand before coding:** summary → graph → source. State which existing process/case/form/bean your feature builds on.
- **Verify, don't hallucinate:** Flowable APIs differ across versions — confirm class/method names against the actual dependencies and https://documentation.flowable.com; don't invent engine APIs.
- **Match model ↔ code:** a `delegateExpression`/`flowable:class` in a model needs the bean/class to exist (and vice-versa). The graph's unresolved references show mismatches.
- **Keys are contracts:** models/Java/frontend reference definitions by key. Before renaming a key, check the graph for who references it (both directions).
- **Respect access/security:** candidate groups, app/page permissions and security policies are part of the feature.
- **Minimal, consistent changes:** mirror existing patterns; touch only what's necessary.

**Common Flowable pitfalls (the knowledge gap):** don't invent engine APIs (verify against deps/docs);
don't hand-edit the exported app `.zip` (model changes go via Design); mind variable scope
(`setVariable` vs `setVariableLocal`); never rename a definition `key` without checking who references it
(both directions); don't forget candidate groups / access on new tasks & pages.
"""
}
