package com.flowable.atlas.render

import java.io.File

/**
 * The Markdown OVERVIEW report — a byte-exact port of `flowable_atlas.py` `render(result, root)`
 * plus its helper `_render_stage` (~lines 4010-4381).
 *
 * `result` is the raw (un-normalized) map produced by [com.flowable.atlas.graph.Atlas.extract]; its
 * values are JSON-shaped (Map / List / String / Number / Boolean / null) and their insertion order is
 * significant — it is what Python's f-string report iterates over. Numbers are formatted the way
 * Python's f-strings format them (integral values print without a trailing `.0`), containers/None
 * print with Python `str()` / `repr()` semantics (`None`, `True`/`False`, `['a', 'b']`,
 * `{'k': 'v'}`), and the result is returned WITHOUT a trailing newline (matching `"\n".join(L)`).
 */
object OverviewRenderer {

    /** Well-known Flowable platform service-task beans (engine-provided, not project source). */
    private val FLOWABLE_PLATFORM_BEANS = setOf(
        "initVariablesService", "dataObjectServiceTask", "generateDocumentService",
        "createDocumentService", "serviceRegistryService", "agentService",
        "sendEventServiceTask", "auditLogService", "decisionServiceTask",
        "caseServiceTask", "httpServiceTask", "scriptServiceTask", "mailServiceTask",
    )

    /** Interfaces that mark a class as Flowable "glue" code. */
    private val GLUE_INTERFACES = setOf(
        "JavaDelegate", "ExecutionListener", "TaskListener", "ActivityBehavior",
        "PlanItemJavaDelegate", "PlanItemActivityBehavior", "CaseInstanceLifecycleListener",
        "PlanItemInstanceLifecycleListener", "DelegatePlanItemActivityBehavior",
        "AbstractServiceTask", "JavaDelegatePlanItem", "FlowableEventListener",
    )

    // model type → normalized graph/index node type (bpmn→process, cmmn→case, …).
    private val NORMALIZE_TYPE = com.flowable.atlas.parsing.ModelKinds.NORMALIZE_TYPE

    fun render(result: Map<String, Any?>, root: File): String {
        val L = ArrayList<String>()
        fun hdr(n: Int, title: String) = L.add("## $n. $title\n")

        val s = asMap(result["stats"])
        val projName = root.absoluteFile.name
        L.add("# Flowable App Overview — `$projName`\n")
        L.add(
            "_Scanned ${pyStr(s["models"])} model files, ${pyStr(s["archives"])} archives, " +
                "${pyStr(s["java"])} Java files, ${pyStr(s["endpoints"])} REST endpoints. " +
                "Generated by flowable_project_overview.py._\n"
        )

        // Apps & inventory
        val apps = asList(result["apps"])
        if (apps.isNotEmpty()) {
            L.add("## 1. Apps\n")
            for (aAny in apps) {
                val a = asMap(aAny)
                L.add("### ${pyStr(a["name"])} (`${pyStr(a["key"])}`) — `${pyStr(a["file"])}`")
                if (truthy(a["description"])) L.add("> ${pyStr(a["description"])}")
                L.add(
                    "- palette: `${pyStr(a["paletteDefinitionCategory"])}`, " +
                        "variables: ${asList(a["variables"]).size}, models: ${asList(a["childModels"]).size}"
                )
                for (cmAny in asList(a["childModels"])) {
                    val cm = asMap(cmAny)
                    val norm = NORMALIZE_TYPE[cm["type"] as? String] ?: cm["type"]
                    val loc = asMap(result["modelIndex"])["${pyStr(norm)}:${pyStr(cm["key"])}"]
                    L.add(
                        "    - ${pyStr(cm["type"])} `${pyStr(cm["key"])}`" +
                            (if (truthy(loc)) " → `${pyStr(loc)}`" else " → _(not found)_")
                    )
                }
                L.add("")
            }
        }

        // Processes
        val processes = asList(result["processes"])
        if (processes.isNotEmpty()) {
            hdr(2, "Processes (BPMN)")
            for (pAny in processes) {
                val p = asMap(pAny)
                L.add("### ${orE(p["name"])} (`${pyStr(p["key"])}`) — `${pyStr(p["file"])}`")
                if (truthy(p["documentation"])) L.add("> ${pyStr(p["documentation"])}")
                if (truthy(p["candidateStarterGroups"]))
                    L.add("- starter groups: `${pyStr(p["candidateStarterGroups"])}`")
                for (utAny in asList(p["userTasks"])) {
                    val ut = asMap(utAny)
                    val extra = if (truthy(ut["formKey"])) " form=`${pyStr(ut["formKey"])}`" else ""
                    L.add(
                        "- 👤 userTask `${pyStr(ut["id"])}` ${orE(ut["name"])}$extra" +
                            (if (truthy(ut["assignee"])) " assignee=${pyStr(ut["assignee"])}" else "")
                    )
                }
                for (stAny in asList(p["serviceTasks"])) {
                    val st = asMap(stAny)
                    val impl = orAny(st["class"], st["delegateExpression"], st["expression"], st["type"], "?")
                    val rv = if (truthy(st["resultVariable"])) " → var `${pyStr(st["resultVariable"])}`" else ""
                    L.add("- ⚙️ serviceTask `${pyStr(st["id"])}` ${orE(st["name"])} → ${pyStr(impl)}$rv")
                }
                for (rtAny in asList(p["ruleTasks"])) {
                    val rt = asMap(rtAny)
                    L.add("- 📊 ruleTask `${pyStr(rt["id"])}` → decision `${pyStr(rt["decisionRef"])}`")
                }
                for (caAny in asList(p["callActivities"])) {
                    val ca = asMap(caAny)
                    val io = asList(ca["inOut"]).joinToString("") {
                        val m = asMap(it)
                        " ${pyStr(m["dir"])}(${pyStr(m["source"])}→${pyStr(m["target"])})"
                    }
                    L.add("- 📞 callActivity `${pyStr(ca["id"])}` → process `${pyStr(ca["calledElement"])}`$io")
                }
                for (miAny in asList(p["multiInstance"])) {
                    val mi = asMap(miAny)
                    L.add(
                        "- 🔁 multi-instance on `${pyStr(mi["activity"])}` collection=`${pyStr(mi["collection"])}` " +
                            "elementVar=`${pyStr(mi["elementVariable"])}`"
                    )
                }
                for (evAny in asList(p["events"])) {
                    val ev = asMap(evAny)
                    val d = if (truthy(ev["def"]))
                        " (${pyStr(ev["def"])}${if (truthy(ev["value"])) "=" + pyStr(ev["value"]) else ""})"
                    else ""
                    L.add("- 🔔 ${pyStr(ev["type"])}$d `${pyStr(ev["id"])}` ${orE(ev["name"])}")
                }
                for (lsAny in asList(p["listeners"])) {
                    val ls = asMap(lsAny)
                    val impl = orAny(ls["class"], ls["delegateExpression"], ls["expression"])
                    if (truthy(impl)) L.add("- 🎧 ${pyStr(ls["kind"])} [${pyStr(ls["event"])}] → ${pyStr(impl)}")
                }
                for (cAny in asList(p["conditions"])) {
                    val c = asMap(cAny)
                    L.add("    - flow ${pyStr(c["from"])}→${pyStr(c["to"])}: `${pyStr(c["condition"])}`")
                }
                L.add("")
            }
        }

        // Cases
        val cases = asList(result["cases"])
        if (cases.isNotEmpty()) {
            hdr(3, "Cases (CMMN)")
            for (cAny in cases) {
                val c = asMap(cAny)
                L.add("### ${orE(c["name"])} (`${pyStr(c["key"])}`) — `${pyStr(c["file"])}`")
                if (truthy(c["documentation"])) L.add("> ${pyStr(c["documentation"])}")
                for (mrAny in asList(c["modelRefs"])) {
                    val mr = asMap(mrAny)
                    L.add("- ${pyStr(mr["rel"])}: `${pyStr(mr["key"])}`")
                }
                if (truthy(c["planModel"])) renderStage(asMap(c["planModel"]), L, 1)
                for (sAny in asList(c["sentries"])) {
                    val sen = asMap(sAny)
                    val cond = if (truthy(sen["condition"])) " if `${pyStr(sen["condition"])}`" else ""
                    L.add(
                        "- 🚪 sentry `${pyStr(sen["id"])}`$cond" +
                            (if (truthy(sen["onParts"])) " on ${pyStr(sen["onParts"])}" else "")
                    )
                }
                for (eAny in asList(c["eventListeners"])) {
                    val e = asMap(eAny)
                    val t = if (truthy(e["timer"])) " timer=`${pyStr(e["timer"])}`" else ""
                    L.add("- ⏰ ${pyStr(e["type"])} `${pyStr(e["id"])}`$t")
                }
                L.add("")
            }
        }

        // Decisions
        val decisions = asList(result["decisions"])
        if (decisions.isNotEmpty()) {
            hdr(4, "Decisions (DMN)")
            for (dAny in decisions) {
                val d = asMap(dAny)
                L.add(
                    "- `${pyStr(d["key"])}` (${pyStr(d["hitPolicy"])}, ${pyStr(d["ruleCount"])} rules) — " +
                        "in: ${pyStr(d["inputs"])}, out: ${pyStr(d["outputs"])} — `${pyStr(d["file"])}`"
                )
            }
            L.add("")
        }

        // Forms & Pages
        val forms = asList(result["forms"])
        if (forms.isNotEmpty()) {
            hdr(5, "Forms & Pages")
            for (fAny in forms) {
                val f = asMap(fAny)
                L.add("### ${orE(f["name"])} (`${pyStr(f["key"])}`) — `${pyStr(f["file"])}`")
                for (fldAny in asList(f["fields"])) {
                    val fld = asMap(fldAny)
                    val b = if (truthy(fld["value"])) " ← `${pyStr(fld["value"])}`" else ""
                    val req = if (truthy(fld["required"])) " *(req)*" else ""
                    L.add("- `${pyStr(fld["id"])}` [${pyStr(fld["type"])}] ${orE(fld["label"])}$req$b")
                }
                val outcomes = asList(f["outcomes"])
                if (outcomes.isNotEmpty()) {
                    L.add(
                        "- outcomes: " + outcomes.map { asMap(it) }.filter { truthy(it["value"]) }
                            .joinToString(", ") { "`${pyStr(it["value"])}`" }
                    )
                }
                for (dsAny in asList(f["dataSources"])) {
                    L.add("- 🔌 data source: ${pyStr(dsAny)}")
                }
                for (sfAny in asList(f["subforms"])) {
                    L.add("- 📑 subform → `${pyStr(sfAny)}`")
                }
                L.add("")
            }
        }

        // Data objects
        val dataObjects = asList(result["dataObjects"])
        if (dataObjects.isNotEmpty()) {
            L.add("## 5b. Data objects\n")
            for (dAny in dataObjects) {
                val d = asMap(dAny)
                val flds = asList(d["fields"])
                val preview = flds.take(12).joinToString(", ") { pyStr(it) } + (if (flds.size > 12) " …" else "")
                val table = if (truthy(d["serviceTableName"])) " (table `${pyStr(d["serviceTableName"])}`)" else ""
                L.add(
                    "- `${pyStr(d["key"])}` (${pyStr(orAny(d["dataObjectType"], "dataObject"))})$table " +
                        "[${flds.size} fields${if (truthy(preview)) ": $preview" else ""}] — `${pyStr(d["file"])}`"
                )
            }
            L.add("")
        }

        // Data dictionaries
        val dictionaries = asList(result["dictionaries"])
        if (dictionaries.isNotEmpty()) {
            L.add("## 5c. Data dictionaries\n")
            for (dAny in dictionaries) {
                val d = asMap(dAny)
                L.add("- `${pyStr(d["key"])}` — types: ${pyStr(d["types"])} — `${pyStr(d["file"])}`")
            }
            L.add("")
        }

        // Other models
        val others = asList(result["others"])
        if (others.isNotEmpty()) {
            L.add("## 5d. Other models (queries, templates, policies, sequences, …)\n")
            val byType = LinkedHashMap<String, MutableList<Map<String, Any?>>>()
            for (oAny in others) {
                val o = asMap(oAny)
                val mtype = pyStr(if (o.containsKey("modelType")) o["modelType"] else "?")
                byType.getOrPut(mtype) { mutableListOf() }.add(o)
            }
            for (mtype in byType.keys.sorted()) {
                L.add("**$mtype** (${byType[mtype]!!.size}):")
                for (o in byType[mtype]!!) {
                    L.add("- `${pyStr(o["key"])}` ${orE(o["name"])} — `${pyStr(o["file"])}`")
                }
            }
            L.add("")
        }

        // Agents / Bots
        val agents = asList(result["agents"])
        if (agents.isNotEmpty()) {
            hdr(6, "Agents / Bots")
            for (aAny in agents) {
                val a = asMap(aAny)
                L.add("### `${pyStr(a["key"])}` — ${orE(a["name"])} (${pyStr(a["type"])}) — `${pyStr(a["file"])}`")
                L.add(
                    "- model: ${pyStr(a["aiVendor"])}/${pyStr(a["modelName"])} (temp ${pyStr(a["temperature"])}), " +
                        "apiEndpoint=${pyStr(a["enableApiEndpoint"])}"
                )
                if (truthy(a["knowledgeBase"])) L.add("- 📚 knowledgeBase → `${pyStr(a["knowledgeBase"])}`")
                for (tAny in asList(a["tools"])) {
                    val t = asMap(tAny)
                    L.add("- 🛠️ tool (${pyStr(t["type"])}) → `${pyStr(t["key"])}`")
                }
                for (opAny in asList(a["operations"])) {
                    val op = asMap(opAny)
                    L.add("- op `${pyStr(op["key"])}`: ${pyStr(orAny(op["systemMessage"], op["userMessage"], ""))}")
                }
                L.add("")
            }
        }

        // Integration
        hdr(7, "Integration: Services, Channels, Events & REST")
        val services = asList(result["services"])
        if (services.isNotEmpty()) {
            L.add("### Service models (.service)")
            for (svAny in services) {
                val sv = asMap(svAny)
                L.add(
                    "- **${pyStr(sv["name"])}** (`${pyStr(sv["key"])}`, ${pyStr(sv["type"])}) " +
                        "base=`${pyStr(sv["baseUrl"])}` auth=${pyStr(sv["auth"])} — `${pyStr(sv["file"])}`"
                )
                for (opAny in asList(sv["operations"])) {
                    val op = asMap(opAny)
                    L.add(
                        "    - `${pyStr(op["method"])}` ${pyStr(orAny(op["fullUrl"], op["url"]))} " +
                            "(op `${pyStr(op["key"])}`)"
                    )
                }
            }
            L.add("")
        }
        val channels = asList(result["channels"])
        if (channels.isNotEmpty()) {
            L.add("### Channels (.channel)")
            for (chAny in channels) {
                val ch = asMap(chAny)
                L.add(
                    "- `${pyStr(ch["key"])}` ${pyStr(ch["channelType"])}/${pyStr(ch["type"])} " +
                        "topics=${pyStr(ch["topics"])} dest=${pyStr(ch["destination"])} — `${pyStr(ch["file"])}`"
                )
            }
            L.add("")
        }
        val eventsList = asList(result["events"])
        if (eventsList.isNotEmpty()) {
            L.add("### Events (.event)")
            for (evAny in eventsList) {
                val ev = asMap(evAny)
                L.add("- `${pyStr(ev["key"])}` payload=${pyStr(ev["payload"])} correlation=${pyStr(ev["correlation"])}")
            }
            L.add("")
        }
        val restCalls = asList(result["restCalls"])
        if (restCalls.isNotEmpty()) {
            L.add("### REST endpoints CALLED by the app (→ matched code)")
            for (rcAny in restCalls) {
                val rc = asMap(rcAny)
                val src = if (truthy(rc["where"])) "${pyStr(rc["source"])}/${pyStr(rc["where"])}" else pyStr(rc["source"])
                L.add("- `${pyStr(rc["method"])}` ${pyStr(rc["url"])}  _(from ${pyStr(rc["kind"])} `$src`)_")
                val matches = asList(rc["matches"])
                for (m in matches) L.add("    - ✅ served by ${pyStr(m)}")
                if (matches.isEmpty())
                    L.add("    - ⚠️ no matching controller in project (external or unimplemented)")
            }
            L.add("")
        }

        // Java glue
        hdr(8, "Java glue code")
        val javaGlue = asList(result["javaGlue"])
        if (javaGlue.isNotEmpty()) {
            L.add("### Delegates / listeners (model-referenced classes)")
            for (jcAny in javaGlue) {
                val jc = asMap(jcAny)
                val inter = (asList(jc["interfaces"]).mapNotNull { it as? String }.toSet() intersect GLUE_INTERFACES).sorted()
                L.add("- `${pyStr(jc["fqn"])}` implements ${pyStr(inter)} — `${pyStr(jc["file"])}:${pyStr(jc["line"])}`")
            }
            L.add("")
        }
        val javaControllers = asList(result["javaControllers"])
        if (javaControllers.isNotEmpty()) {
            L.add("### REST controllers & endpoints")
            for (jcAny in javaControllers) {
                val jc = asMap(jcAny)
                L.add("- **${pyStr(jc["primary"])}** — `${pyStr(jc["file"])}`")
                for (epAny in asList(jc["endpoints"])) {
                    val ep = asMap(epAny)
                    L.add("    - `${pyStr(ep["http"])}` ${pyStr(ep["path"])} → ${pyStr(ep["handler"])}() (line ${pyStr(ep["line"])})")
                }
            }
            L.add("")
        }

        // Model <-> code resolved references
        hdr(9, "Resolved references (model → code / model)")
        val resolvedRefs = asList(result["resolvedRefs"]).map { asMap(it) }
        val codeRefs = resolvedRefs.filter { it["targetType"] == "bean" || it["targetType"] == "class" }
        val modelRefs = resolvedRefs.filter { it["targetType"] == "model" }
        if (codeRefs.isNotEmpty()) {
            L.add("### Model → Java code")
            for (r in codeRefs) {
                L.add("- `${pyStr(r["from"])}` [${pyStr(r["rel"])}] `${pyStr(r["value"])}` → ${pyStr(r["target"])}")
            }
            L.add("")
        }
        if (modelRefs.isNotEmpty()) {
            L.add("### Model → Model")
            for (r in modelRefs) {
                L.add("- `${pyStr(r["from"])}` —${pyStr(r["rel"])}→ ${pyStr(r["kind"])} `${pyStr(r["value"])}` (`${pyStr(r["target"])}`)")
            }
            L.add("")
        }

        // Unresolved
        hdr(10, "Unresolved references (external / library / missing)")
        val unresolvedRefs = asList(result["unresolvedRefs"]).map { asMap(it) }
        val groups = LinkedHashMap<Pair<String, String>, MutableList<Map<String, Any?>>>()
        for (r in unresolvedRefs) {
            groups.getOrPut(Pair(pyStr(r["kind"]), pyStr(r["value"]))) { mutableListOf() }.add(r)
        }
        val platform = groups.filterKeys { it.first == "bean" && it.second in FLOWABLE_PLATFORM_BEANS }
        val othersG = groups.filterKeys { it !in platform.keys }
        val tupleCmp = compareBy<Map.Entry<Pair<String, String>, *>>({ it.key.first }, { it.key.second })
        if (platform.isNotEmpty()) {
            L.add("### Expected Flowable platform beans (provided by the engine, not project code)")
            for ((k, rs) in platform.entries.sortedWith(tupleCmp)) {
                val n = rs.map { pyStr(it["from"]) }.toSet().size
                L.add("- `${k.second}` — referenced by $n model(s)")
            }
            L.add("")
        }
        if (othersG.isNotEmpty()) {
            L.add("### Other unresolved — review (external dependency, typo, or missing)")
            for ((k, rs) in othersG.entries.sortedWith(tupleCmp)) {
                val froms = rs.map { pyStr(it["from"]) }.toSortedSet().toList()
                val more = if (froms.size > 1) " (+${froms.size - 1} more)" else ""
                L.add("- [${k.first}] `${k.second}` — from `${froms[0]}`$more")
            }
            L.add("")
        }
        if (unresolvedRefs.isEmpty()) {
            L.add("_None — every reference resolved within the project._\n")
        }

        // Access & user groups
        hdr(11, "Access & user groups (who can do what)")
        val acc = asList(result["access"]).map { asMap(it) }
        val groupsAll = asList(result["groups"])
        if (groupsAll.isNotEmpty()) {
            L.add(
                "**All groups/roles referenced (${groupsAll.size}):** " +
                    groupsAll.joinToString(", ") { "`${pyStr(it)}`" } + "\n"
            )
        }
        val appAcc = acc.filter { it["scope"] == "app" || it["scope"] == "page" }
        if (appAcc.isNotEmpty()) {
            L.add("### App / page access")
            for (a in appAcc) {
                val who0 = asList(a["groups"]).map { pyStr(it) } + asList(a["users"]).map { "user:${pyStr(it)}" }
                val who = if (who0.isNotEmpty()) who0.joinToString(", ") else "(everyone)"
                L.add("- ${pyStr(a["modelType"])} `${pyStr(a["model"])}`: $who")
            }
            L.add("")
        }
        val starts = acc.filter { it["action"] == "start" }
        if (starts.isNotEmpty()) {
            L.add("### Who can start (processes & cases)")
            for (a in starts.sortedBy { pyStr(it["model"]) }) {
                val who0 = asList(a["groups"]).map { pyStr(it) } + asList(a["users"]).map { pyStr(it) }
                val who = if (who0.isNotEmpty()) who0.joinToString(", ") else "(no restriction)"
                L.add("- ${pyStr(a["modelType"])} `${pyStr(a["model"])}` ← $who")
            }
            L.add("")
        }
        val assigns = acc.filter { it["action"] == "assign" }
        if (assigns.isNotEmpty()) {
            L.add("### Task assignment (candidate groups / assignees per model)")
            val bym = LinkedHashMap<String, MutableSet<String>>()
            for (a in assigns) {
                val set = bym.getOrPut(pyStr(a["model"])) { mutableSetOf() }
                set.addAll(asList(a["groups"]).map { pyStr(it) })
                set.addAll(asList(a["users"]).map { pyStr(it) })
            }
            for (model in bym.keys.sorted()) {
                L.add("- `$model`: ${bym[model]!!.sorted().joinToString(", ")}")
            }
            L.add("")
        }
        val doAcc = acc.filter { it["modelType"] == "dataObject" }
        if (doAcc.isNotEmpty()) {
            L.add("### Data object access (who may query/create/update/delete)")
            val bym = LinkedHashMap<String, MutableList<Map<String, Any?>>>()
            for (a in doAcc) bym.getOrPut(pyStr(a["model"])) { mutableListOf() }.add(a)
            for (model in bym.keys.sorted()) {
                val perms = bym[model]!!.joinToString("; ") { a ->
                    val g = asList(a["groups"]).joinToString("/") { pyStr(it) }
                    "${pyStr(a["action"])}=${if (g.isNotEmpty()) g else "?"}"
                }
                L.add("- `$model`: $perms")
            }
            L.add("")
        }
        val policies = asList(result["policies"]).map { asMap(it) }
        if (policies.isNotEmpty()) {
            L.add("### Security policies")
            for (p in policies) {
                L.add("- `${pyStr(p["key"])}` — `${pyStr(p["file"])}`")
                for (permAny in asList(p["permissions"])) {
                    val perm = asMap(permAny)
                    val roles = asList(perm["roles"]).map { pyStr(it) }
                    L.add("    - ${pyStr(perm["key"])}: ${if (roles.isNotEmpty()) roles.joinToString(", ") else "(none)"}")
                }
            }
            L.add("")
        }
        if (acc.isEmpty() && policies.isEmpty()) {
            L.add("_No explicit access restrictions found._\n")
        }

        // Code map
        hdr(12, "Code map (where things live)")
        if (agents.isNotEmpty()) {
            L.add("**Agents / bots (models):**")
            for (aAny in agents) {
                val a = asMap(aAny)
                L.add("- `${pyStr(a["key"])}` — `${pyStr(a["file"])}`")
            }
        }
        if (services.isNotEmpty()) {
            L.add("**Service models (.service):**")
            for (svAny in services) {
                val sv = asMap(svAny)
                L.add("- `${pyStr(sv["key"])}` (${pyStr(sv["type"])}) base=`${pyStr(sv["baseUrl"])}` — `${pyStr(sv["file"])}`")
            }
        }
        // Models grouped by folder
        val folders = LinkedHashMap<String, LinkedHashMap<String, Int>>()
        val bucketLabel = listOf(
            "processes" to "bpmn", "cases" to "cmmn", "decisions" to "dmn",
            "forms" to "form", "dataObjects" to "data", "services" to "service",
            "agents" to "agent", "channels" to "channel", "events" to "event",
            "dictionaries" to "dict", "policies" to "policy", "actions" to "action",
            "liquibase" to "liquibase", "others" to "other",
        )
        for ((bucket, label) in bucketLabel) {
            for (oAny in asList(result[bucket])) {
                val o = asMap(oAny)
                val fpath = (o["file"] as? String) ?: ""
                val head = fpath.split("!")[0]
                val folder = if (head.contains("/")) head.substringBeforeLast("/") else "."
                val fm = folders.getOrPut(folder) { LinkedHashMap() }
                fm[label] = (fm[label] ?: 0) + 1
            }
        }
        if (folders.isNotEmpty()) {
            L.add("\n**Models by folder:**")
            for (folder in folders.keys.sorted()) {
                val counts = folders[folder]!!.entries
                    .sortedWith(compareBy({ it.key }, { it.value }))
                    .joinToString(", ") { "${it.value} ${it.key}" }
                L.add("- `$folder/` — $counts")
            }
        }
        // Java by role
        val jbr = asMap(result["javaByRole"])
        if (jbr.isNotEmpty()) {
            L.add("\n**Java code by role:**")
            for (role in listOf(
                "controller", "delegate", "listener", "service", "repository",
                "configuration", "component", "other",
            )) {
                val items = asList(jbr[role])
                if (items.isEmpty()) continue
                if (role == "other") {
                    L.add("\n_other (no Spring/Flowable role — DTOs, utils, …): ${items.size} classes_")
                    continue
                }
                L.add("\n_$role (${items.size}):_")
                for (jc in items.map { asMap(it) }.sortedBy { pyStr(it["fqn"]) }.take(80)) {
                    var iface = ""
                    if (role == "delegate" || role == "listener") {
                        val rel = asList(jc["interfaces"]).mapNotNull { it as? String }
                            .filter { it.endsWith("Listener") || it in GLUE_INTERFACES }.sorted()
                        iface = if (rel.isNotEmpty()) " [${rel.joinToString(", ")}]" else ""
                    }
                    L.add("- `${pyStr(jc["fqn"])}`$iface — `${pyStr(jc["file"])}:${pyStr(jc["line"])}`")
                }
                if (items.size > 80) L.add("- … (+${items.size - 80} more)")
            }
        }
        L.add("")

        // Variables / expressions
        hdr(13, "Variables, beans & expressions")
        val variables = asList(result["variables"])
        if (variables.isNotEmpty()) {
            L.add("**Variables:** " + variables.joinToString(", ") { "`${pyStr(it)}`" } + "\n")
        }
        val beans = asList(result["beans"])
        if (beans.isNotEmpty()) {
            L.add("**Beans/objects with method calls:** " + beans.joinToString(", ") { "`${pyStr(it)}`" } + "\n")
        }
        val delegateClasses = asList(result["delegateClasses"])
        if (delegateClasses.isNotEmpty()) {
            L.add(
                "**JavaDelegate/listener classes referenced:** " +
                    delegateClasses.joinToString(", ") { "`${pyStr(it)}`" } + "\n"
            )
        }
        val expressions = asList(result["expressions"])
        if (expressions.isNotEmpty()) {
            L.add("<details><summary>All expressions (\${ } / #{ })</summary>\n")
            for (ex in expressions) L.add("- `${pyStr(ex)}`")
            L.add("\n</details>\n")
        }

        // Warnings
        val warnings = asList(result["warnings"])
        if (warnings.isNotEmpty()) {
            hdr(14, "Warnings (${warnings.size})")
            for (w in warnings.take(200)) L.add("- ${pyStr(w)}")
            if (warnings.size > 200)
                L.add("- … (+${warnings.size - 200} more — see `diagnostics` in graph.json)")
        }
        return L.joinToString("\n")
    }

    /** Port of `_render_stage(node, L, depth)`. */
    private fun renderStage(node: Map<String, Any?>, L: MutableList<String>, depth: Int) {
        val ind = "    ".repeat(depth)
        L.add("$ind- 📁 **${pyStr(node["type"])}** ${pyStr(orAny(node["name"], node["id"], ""))}")
        for (chAny in asList(node["children"])) {
            val ch = asMap(chAny)
            var rules = ""
            if (truthy(ch["rules"])) {
                rules = " " + asMap(ch["rules"]).entries.joinToString(", ") { "${pyStr(it.key)}=${pyStr(it.value)}" }
            }
            if (ch.containsKey("children")) {
                renderStage(ch, L, depth + 1)
            } else {
                var extra = ""
                for (k in listOf(
                    "assignee", "formKey", "processRef", "caseRef", "decisionRef",
                    "serviceModelKey", "agentModelKey", "dataObjectKey",
                )) {
                    if (truthy(ch[k])) extra += " $k=`${pyStr(ch[k])}`"
                }
                L.add("$ind    - ${pyStr(ch["type"])} ${pyStr(orAny(ch["name"], ch["id"], ""))}$extra$rules")
            }
        }
    }

    // ---- Python str()/repr()/truthiness helpers -------------------------------------------------

    @Suppress("UNCHECKED_CAST")
    private fun asMap(v: Any?): Map<String, Any?> = (v as? Map<String, Any?>) ?: emptyMap()

    private fun asList(v: Any?): List<Any?> = (v as? List<Any?>) ?: emptyList()

    /** Python truthiness. */
    private fun truthy(v: Any?): Boolean = when (v) {
        null -> false
        is Boolean -> v
        is Number -> v.toDouble() != 0.0
        is String -> v.isNotEmpty()
        is Collection<*> -> v.isNotEmpty()
        is Map<*, *> -> v.isNotEmpty()
        else -> true
    }

    /** Python `a or b or …` — first truthy operand, else the last. */
    private fun orAny(vararg vals: Any?): Any? {
        for (v in vals) if (truthy(v)) return v
        return vals.last()
    }

    /** `v or ''` rendered through str(). */
    private fun orE(v: Any?): String = if (truthy(v)) pyStr(v) else ""

    /** Format a number the way a Python f-string does (integral values drop the trailing `.0`). */
    private fun numStr(n: Number): String = when (n) {
        is Double -> if (n.isFinite() && n == Math.floor(n)) n.toLong().toString() else n.toString()
        is Float -> { val d = n.toDouble(); if (d.isFinite() && d == Math.floor(d)) d.toLong().toString() else n.toString() }
        else -> n.toString()
    }

    /** Python `str(v)`. */
    private fun pyStr(v: Any?): String = when (v) {
        null -> "None"
        is Boolean -> if (v) "True" else "False"
        is Number -> numStr(v)
        is String -> v
        is List<*> -> pyRepr(v)
        is Map<*, *> -> pyRepr(v)
        else -> v.toString()
    }

    /** Python `repr(v)`. */
    private fun pyRepr(v: Any?): String = when (v) {
        null -> "None"
        is Boolean -> if (v) "True" else "False"
        is Number -> numStr(v)
        is String -> reprStr(v)
        is List<*> -> v.joinToString(", ", "[", "]") { pyRepr(it) }
        is Map<*, *> -> v.entries.joinToString(", ", "{", "}") { "${pyRepr(it.key)}: ${pyRepr(it.value)}" }
        else -> v.toString()
    }

    /** Python `repr(str)` — single quotes unless the string has a `'` but no `"`. */
    private fun reprStr(str: String): String {
        val quote = if (str.contains('\'') && !str.contains('"')) '"' else '\''
        val sb = StringBuilder()
        sb.append(quote)
        for (c in str) {
            when (c) {
                '\\' -> sb.append("\\\\")
                '\n' -> sb.append("\\n")
                '\r' -> sb.append("\\r")
                '\t' -> sb.append("\\t")
                quote -> sb.append('\\').append(quote)
                else -> sb.append(c)
            }
        }
        sb.append(quote)
        return sb.toString()
    }
}
