package com.flowable.atlas.render

import com.flowable.atlas.model.DesignTerms
import java.io.File

/**
 * The Markdown OVERVIEW report — every model, relationship and the access map.
 *
 * `result` is the raw (un-normalized) map produced by [com.flowable.atlas.graph.Atlas.extract]; its
 * values are JSON-shaped (Map / List / String / Number / Boolean / null). Numbers print without a
 * trailing `.0` ([numStr]); the result is returned WITHOUT a trailing newline (the caller adds it).
 *
 * Originally a byte-exact port of `flowable_atlas.py`, which is why [pyStr] exists. Scalars still go
 * through it; **lists, maps and optional values must go through [Fmt] instead** — via `pyStr` they
 * printed as `['a', 'b']` / `{'k': 'v'}` / `None`, which is Python's debugging output, not a report.
 * `MarkdownHygieneTest` fails if any of those reach the page.
 */
object OverviewRenderer {

    /** Well-known Flowable platform service-task beans (engine-provided, not project source). */
    private val FLOWABLE_PLATFORM_BEANS = setOf(
        "initVariablesService", "dataObjectServiceTask", "generateDocumentService",
        "createDocumentService", "serviceRegistryService", "agentService",
        "sendEventServiceTask", "auditLogService", "decisionServiceTask",
        "caseServiceTask", "httpServiceTask", "scriptServiceTask", "mailServiceTask",
    )

    /** Interfaces that mark a class as Flowable "glue" code. */
    private val GLUE_INTERFACES = setOf(
        "JavaDelegate", "ExecutionListener", "TaskListener", "ActivityBehavior",
        "PlanItemJavaDelegate", "PlanItemActivityBehavior", "CaseInstanceLifecycleListener",
        "PlanItemInstanceLifecycleListener", "DelegatePlanItemActivityBehavior",
        "AbstractServiceTask", "JavaDelegatePlanItem", "FlowableEventListener",
    )

    // model type → normalized graph/index node type (bpmn→process, cmmn→case, …).
    private val NORMALIZE_TYPE = com.flowable.atlas.parsing.ModelKinds.NORMALIZE_TYPE

    /**
     * Findings listed per check before eliding the rest. A project with 400 script-inferred variables
     * should not push its two broken expressions off the page — and the full list is in `graph.json`.
     */
    private const val FINDINGS_PER_CHECK = 20

    /** Node types that already have a section of their own, so the "also in the graph" line skips them. */
    private val REPORTED_NODE_TYPES = setOf(
        "app", "process", "case", "decision", "form", "page", "dataObject", "dataDictionary",
        "service", "agent", "channel", "event", "action", "securityPolicy", "liquibase",
        "java", "endpoint", "group", "variable", "expression", "binding", "external",
    )

    /**
     * Caps for the sections that grow linearly with the project. On a real 359-model app the report was
     * 373 KB / 4019 lines — past the point where anyone, human or model, reads it — because these lists
     * were unbounded. Each cap ends in a pointer to the graph, which holds the full set.
     */
    private const val FORM_FIELDS_LISTED = 40
    private const val RESOLVED_REFS_LISTED = 120

    /** Rule rows listed per decision table before eliding — enough to see the shape of the logic. */
    private const val DMN_RULES_LISTED = 12

    /** Column rows listed per service in the data-layer chain (only the problem rows are listed). */
    private const val SCHEMA_ROWS_LISTED = 12

    /** A parameter is either a plain name or `{name, type, …}` depending on the model. */
    private fun paramName(v: Any?): String = when (v) {
        is Map<*, *> -> (v["name"] ?: v["key"] ?: "").toString()
        else -> v?.toString() ?: ""
    }

    /** Caps for §13. A 381-variable project must not turn the report into a variable dictionary. */
    private const val VARIABLES_LISTED = 60
    private const val EXPRESSION_GROUPS = 40
    private const val EXPRESSIONS_PER_GROUP = 8

    fun render(result: Map<String, Any?>, root: File): String {
        val L = ArrayList<String>()
        fun hdr(n: Int, title: String) = L.add("## $n. $title\n")

        val s = asMap(result["stats"])
        val projName = root.absoluteFile.name
        L.add("# Flowable App Overview — `$projName`\n")
        val an = Fmt.artifactName(root)
        L.add(
            "_Scanned ${pyStr(s["models"])} model files, ${pyStr(s["archives"])} archives, " +
                "${pyStr(s["java"])} Java files, ${pyStr(s["endpoints"])} REST endpoints. " +
                "Generated by Flowable Atlas — regenerate with `atlas <project-dir>`. " +
                // The SVGs are written by the same `--all` run but nothing ever mentioned them.
                "Diagrams of the models that carry layout: `$an.diagrams/*.svg`._\n"
        )

        // Apps & inventory
        val apps = asList(result["apps"])
        if (apps.isNotEmpty()) {
            L.add("## 1. Apps\n")
            for (aAny in apps) {
                val a = asMap(aAny)
                L.add("### ${pyStr(a["name"])} (`${pyStr(a["key"])}`) — `${pyStr(a["file"])}`")
                if (truthy(a["description"])) L.add("> ${pyStr(a["description"])}")
                L.add(
                    Fmt.fields(
                        "palette" to Fmt.codeList(a["paletteDefinitionCategory"]),
                        "variables" to asList(a["variables"]).size.toString(),
                        "models" to asList(a["childModels"]).size.toString(),
                    ).let { "- $it" }
                )
                for (cmAny in asList(a["childModels"])) {
                    val cm = asMap(cmAny)
                    val norm = NORMALIZE_TYPE[cm["type"] as? String] ?: cm["type"]
                    val loc = asMap(result["modelIndex"])["${pyStr(norm)}:${pyStr(cm["key"])}"]
                    L.add(
                        "    - ${pyStr(cm["type"])} `${pyStr(cm["key"])}`" +
                            (if (truthy(loc)) " → `${pyStr(loc)}`" else " → _(not found)_")
                    )
                }
                L.add("")
            }
        }

        // Processes
        val processes = asList(result["processes"])
        if (processes.isNotEmpty()) {
            hdr(2, "Processes (BPMN)")
            for (pAny in processes) {
                val p = asMap(pAny)
                L.add("### ${orE(p["name"])} (`${pyStr(p["key"])}`) — `${pyStr(p["file"])}`")
                if (truthy(p["documentation"])) L.add("> ${pyStr(p["documentation"])}")
                if (truthy(p["candidateStarterGroups"]))
                    L.add("- starter groups: `${pyStr(p["candidateStarterGroups"])}`")
                // Elements are collected first and emitted in **execution order** (see [flowOrder]).
                // Grouped-by-type listing put the start and end events last and left a reader unable to
                // tell what runs after what — the first thing anyone needs to know about a process.
                // `id` is not unique across buckets (a DMN service task is both a serviceTask and a
                // ruleTask), so rows are a list, not a map, and sorting is stable.
                val rows = ArrayList<Triple<String, String, Boolean>>() // (elementId, line, isSubLine)
                var synthetic = 0
                fun row(id: Any?, line: String) {
                    rows.add(Triple(if (truthy(id)) pyStr(id) else "?unnamed-${synthetic++}", line, false))
                }
                fun subRow(id: Any?, line: String) {
                    if (truthy(id)) rows.add(Triple(pyStr(id), line, true))
                }

                for (utAny in asList(p["userTasks"])) {
                    val ut = asMap(utAny)
                    val extra = if (truthy(ut["formKey"])) " form=`${pyStr(ut["formKey"])}`" else ""
                    row(
                        ut["id"],
                        Fmt.join(
                            "- 👤 ${DesignTerms.label("el", "userTask")} `${pyStr(ut["id"])}`",
                            orE(ut["name"]), extra,
                            if (truthy(ut["assignee"])) "assignee=${pyStr(ut["assignee"])}" else "",
                        )
                    )
                }
                for (stAny in asList(p["serviceTasks"])) {
                    val st = asMap(stAny)
                    val impl = orAny(st["class"], st["delegateExpression"], st["expression"], st["type"], "?")
                    val rv = if (truthy(st["resultVariable"])) " → var `${pyStr(st["resultVariable"])}`" else ""
                    row(st["id"], "- ⚙️ ${DesignTerms.label("el", "serviceTask")} `${pyStr(st["id"])}` " +
                        "${orE(st["name"])} → ${pyStr(impl)}$rv")
                }
                // Script tasks were missing from this report entirely — a process could run a script and
                // nothing in the Markdown said so.
                for (stAny in asList(p["scriptTasks"])) {
                    val st = asMap(stAny)
                    val fmt = if (truthy(st["format"])) " (${pyStr(st["format"])})" else ""
                    val rv = if (truthy(st["resultVariable"])) " → var `${pyStr(st["resultVariable"])}`" else ""
                    val probs = asList(st["problems"])
                    val warn = if (probs.isEmpty()) ""
                        else " — ⚠ ${probs.size} syntax finding${if (probs.size > 1) "s" else ""}"
                    row(st["id"], "- 🧾 ${DesignTerms.label("el", "scriptTask")} `${pyStr(st["id"])}` " +
                        "${orE(st["name"])}$fmt$rv$warn")
                }
                for (rtAny in asList(p["ruleTasks"])) {
                    val rt = asMap(rtAny)
                    row(rt["id"], "- 📊 ${DesignTerms.label("el", "serviceTask/dmn")} `${pyStr(rt["id"])}` " +
                        "→ decision table `${pyStr(rt["decisionRef"])}`")
                }
                // Gateways and receive/send/manual tasks are parsed but were never rendered: a branch
                // point missing from the listing makes the flow below it unreadable.
                for (gwAny in asList(p["gateways"])) {
                    val gw = asMap(gwAny)
                    row(gw["id"], Fmt.join(
                        "- ◆ ${DesignTerms.label("el", gw["type"])} `${pyStr(gw["id"])}`", orE(gw["name"]),
                    ))
                }
                for (otAny in asList(p["otherTasks"])) {
                    val ot = asMap(otAny)
                    row(ot["id"], Fmt.join(
                        "- ▫ ${DesignTerms.label("el", ot["type"])} `${pyStr(ot["id"])}`", orE(ot["name"]),
                    ))
                }
                for (spAny in asList(p["subProcesses"])) {
                    val sp = asMap(spAny)
                    row(sp["id"], Fmt.join(
                        "- ▣ ${DesignTerms.label("el", orAny(sp["type"], "subProcess"))} `${pyStr(sp["id"])}`",
                        orE(sp["name"]),
                    ))
                }
                for (caAny in asList(p["callActivities"])) {
                    val ca = asMap(caAny)
                    // `<flowable:in>`/`<flowable:out>` live in the model's flat `parameters` rollup, stamped
                    // with the element that declares them (see Ctx.addParams).
                    val io = asList(p["ioParameters"]).map { asMap(it) }
                        .filter { it["element"] == ca["id"] && it["kind"] in listOf("in", "out") }
                        .joinToString("") { " ${pyStr(it["dir"])}(${pyStr(it["source"])}→${pyStr(it["target"])})" }
                    row(ca["id"], "- 📞 ${DesignTerms.label("el", "callActivity")} `${pyStr(ca["id"])}` " +
                        "→ process `${pyStr(ca["calledElement"])}`$io")
                }
                for (miAny in asList(p["multiInstance"])) {
                    val mi = asMap(miAny)
                    subRow(
                        mi["activity"],
                        "    - 🔁 Multi-instance " + Fmt.fields(
                            "collection" to Fmt.codeList(mi["collection"]),
                            "elementVar" to Fmt.codeList(mi["elementVariable"]),
                        )
                    )
                }
                for (evAny in asList(p["events"])) {
                    val ev = asMap(evAny)
                    val d = if (truthy(ev["def"]))
                        " (${pyStr(ev["def"])}${if (truthy(ev["value"])) "=" + pyStr(ev["value"]) else ""})"
                    else ""
                    row(ev["id"], Fmt.join(
                        "- 🔔 ${DesignTerms.label("el", ev["type"])}$d `${pyStr(ev["id"])}`", orE(ev["name"]),
                    ))
                }
                // Listeners of the process AND of its elements. Only the process-level ones were listed,
                // and a script-only listener was skipped entirely because it has no class/expression —
                // both cases hid code that runs at runtime.
                // Element listeners now sit under their element instead of in one block at the end, so a
                // reader sees the code that runs at a step next to the step.
                fun listenerLine(ls: Map<String, Any?>): String? {
                    val impl = orAny(ls["class"], ls["delegateExpression"], ls["expression"],
                        if (truthy(ls["script"])) "(script)" else null)
                    if (!truthy(impl)) return null
                    return "🎧 ${DesignTerms.label("el", ls["kind"])} [${pyStr(ls["event"])}] → ${pyStr(impl)}"
                }
                for (bucket in ELEMENT_BUCKETS) {
                    for (elAny in asList(p[bucket])) {
                        val el = asMap(elAny)
                        for (lsAny in asList(el["listeners"])) {
                            listenerLine(asMap(lsAny))?.let { subRow(el["id"], "    - $it") }
                        }
                    }
                }

                // --- emit in execution order, each step naming what follows it ---
                val order = flowOrder(p, rows.map { it.first }.distinct())
                val successors = successorsByElement(p)
                val ordered = rows.sortedWith(
                    compareBy({ order[it.first] ?: Int.MAX_VALUE }, { if (it.third) 1 else 0 })
                )
                // An element no sequence flow mentions is *not* the next step of the line above it, even
                // though document order lands it there — say so rather than imply a sequence that the
                // model does not have. (Only worth saying when the process has flows at all.)
                val connected = HashSet<String>()
                for (fAny in asList(p["flows"])) {
                    val f = asMap(fAny)
                    f["from"]?.toString()?.let { connected.add(it) }
                    f["to"]?.toString()?.let { connected.add(it) }
                }
                val hasFlows = connected.isNotEmpty()
                val annotated = HashSet<String>()
                for ((id, line, sub) in ordered) {
                    if (sub) { L.add(line); continue }
                    val next = successors[id]
                    // The same id can be described by two rows (a DMN service task is both); the
                    // successor belongs to the element, so state it once.
                    val suffix = when {
                        !annotated.add(id) -> ""
                        !next.isNullOrEmpty() -> " · next: ${Fmt.cap(next, 6)}"
                        hasFlows && id !in connected -> " · _(no sequence flow — not reachable)_"
                        else -> ""
                    }
                    L.add(line + suffix)
                }
                // Process-level listeners are not steps, so they follow the flow rather than interrupt it.
                for (lsAny in asList(p["listeners"])) listenerLine(asMap(lsAny))?.let { L.add("- $it") }
                L.add("")
            }
        }

        // Cases
        val cases = asList(result["cases"])
        if (cases.isNotEmpty()) {
            hdr(3, "Cases (CMMN)")
            for (cAny in cases) {
                val c = asMap(cAny)
                L.add("### ${orE(c["name"])} (`${pyStr(c["key"])}`) — `${pyStr(c["file"])}`")
                if (truthy(c["documentation"])) L.add("> ${pyStr(c["documentation"])}")
                for (mrAny in asList(c["modelRefs"])) {
                    val mr = asMap(mrAny)
                    L.add("- ${pyStr(mr["rel"])}: `${pyStr(mr["key"])}`")
                }
                // Index the sentries so the plan tree can show each criterion's actual condition.
                val sentryIndex = asList(c["sentries"]).map { asMap(it) }
                    .mapNotNull { sen -> sen["id"]?.toString()?.ifEmpty { null }?.let { it to sen } }
                    .toMap()
                if (truthy(c["planModel"])) renderStage(asMap(c["planModel"]), L, 1, sentryIndex)
                for (sAny in asList(c["sentries"])) {
                    val sen = asMap(sAny)
                    val cond = if (truthy(sen["condition"])) " if `${pyStr(sen["condition"])}`" else ""
                    val on = Fmt.list(sen["onParts"])
                    L.add("- 🚪 Sentry `${pyStr(sen["id"])}`$cond" + (if (on.isNotEmpty()) " on $on" else ""))
                }
                for (eAny in asList(c["eventListeners"])) {
                    val e = asMap(eAny)
                    val t = if (truthy(e["timer"])) " timer=`${pyStr(e["timer"])}`" else ""
                    L.add("- ⏰ ${DesignTerms.label("el", e["type"])} `${pyStr(e["id"])}`$t")
                }
                L.add("")
            }
        }

        // Decisions
        val decisions = asList(result["decisions"])
        if (decisions.isNotEmpty()) {
            hdr(4, "Decision tables (DMN)")
            for (dAny in decisions) {
                val d = asMap(dAny)
                L.add(
                    "- `${pyStr(d["key"])}` (${pyStr(d["hitPolicy"])}, ${pyStr(d["ruleCount"])} rules) — " +
                        "in: ${Fmt.codeList(d["inputs"])} → out: ${Fmt.codeList(d["outputs"])} — " +
                        "`${pyStr(d["file"])}`"
                )
                // The rule rows — the actual business logic. They were parsed into `rules` and then only
                // ever shown in the explorer, so the report described a decision table without saying
                // what it decides.
                val rules = asList(d["rules"]).map { asMap(it) }
                for (r in rules.take(DMN_RULES_LISTED)) {
                    val ins = Fmt.list(r["inputs"], " · ")
                    val outs = Fmt.list(r["outputs"], " · ")
                    val note = if (truthy(r["annotation"])) " _(${pyStr(r["annotation"])})_" else ""
                    L.add("    - when ${ins.ifEmpty { "—" }} → ${outs.ifEmpty { "—" }}$note")
                }
                if (rules.size > DMN_RULES_LISTED) {
                    L.add("    - … (+${rules.size - DMN_RULES_LISTED} more rules)")
                }
                if (d["rulesTruncated"] == true) {
                    L.add("    - _(rule list truncated during parsing — see the model file)_")
                }
            }
            L.add("")
        }

        // Forms & Pages
        val forms = asList(result["forms"])
        if (forms.isNotEmpty()) {
            hdr(5, "Forms & pages")
            for (fAny in forms) {
                val f = asMap(fAny)
                L.add("### ${orE(f["name"])} (`${pyStr(f["key"])}`) — `${pyStr(f["file"])}`")
                val fields = asList(f["fields"])
                for (fldAny in fields.take(FORM_FIELDS_LISTED)) {
                    val fld = asMap(fldAny)
                    val b = if (truthy(fld["value"])) " ← `${pyStr(fld["value"])}`" else ""
                    val req = if (truthy(fld["required"])) " *(req)*" else ""
                    L.add("- `${pyStr(fld["id"])}` [${pyStr(fld["type"])}] ${orE(fld["label"])}$req$b")
                }
                if (fields.size > FORM_FIELDS_LISTED) {
                    L.add("- … (+${fields.size - FORM_FIELDS_LISTED} more fields — `fields` on the form " +
                        "node in `$an.graph.json`)")
                }
                val outcomes = asList(f["outcomes"])
                if (outcomes.isNotEmpty()) {
                    L.add(
                        "- outcomes: " + outcomes.map { asMap(it) }.filter { truthy(it["value"]) }
                            .joinToString(", ") { "`${pyStr(it["value"])}`" }
                    )
                }
                for (dsAny in asList(f["dataSources"])) {
                    L.add("- 🔌 data source: ${Fmt.dataSource(dsAny)}")
                }
                for (sfAny in asList(f["subforms"])) {
                    L.add("- 📑 subform → `${pyStr(sfAny)}`")
                }
                L.add("")
            }
        }

        // Data objects
        val dataObjects = asList(result["dataObjects"])
        if (dataObjects.isNotEmpty()) {
            L.add("## 5b. Data objects\n")
            for (dAny in dataObjects) {
                val d = asMap(dAny)
                val flds = asList(d["fields"])
                val preview = flds.take(12).joinToString(", ") { pyStr(it) } + (if (flds.size > 12) " …" else "")
                val table = if (truthy(d["serviceTableName"])) " (table `${pyStr(d["serviceTableName"])}`)" else ""
                L.add(
                    "- `${pyStr(d["key"])}` (${pyStr(orAny(d["dataObjectType"], "dataObject"))})$table " +
                        "[${flds.size} fields${if (truthy(preview)) ": $preview" else ""}] — `${pyStr(d["file"])}`"
                )
            }
            L.add("")
        }

        // Data dictionaries
        val dictionaries = asList(result["dictionaries"])
        if (dictionaries.isNotEmpty()) {
            L.add("## 5c. Data dictionaries\n")
            for (dAny in dictionaries) {
                val d = asMap(dAny)
                L.add("- `${pyStr(d["key"])}` — types: ${pyStr(d["types"])} — `${pyStr(d["file"])}`")
            }
            L.add("")
        }

        // Other models
        val others = asList(result["others"])
        if (others.isNotEmpty()) {
            L.add("## 5d. Other models (queries, templates, policies, sequences, …)\n")
            val byType = LinkedHashMap<String, MutableList<Map<String, Any?>>>()
            for (oAny in others) {
                val o = asMap(oAny)
                val mtype = pyStr(if (o.containsKey("modelType")) o["modelType"] else "?")
                byType.getOrPut(mtype) { mutableListOf() }.add(o)
            }
            for (mtype in byType.keys.sorted()) {
                L.add("**$mtype** (${byType[mtype]!!.size}):")
                for (o in byType[mtype]!!) {
                    L.add("- `${pyStr(o["key"])}` ${orE(o["name"])} — `${pyStr(o["file"])}`")
                }
            }
            L.add("")
        }

        // Agents / Bots
        val agents = asList(result["agents"])
        if (agents.isNotEmpty()) {
            hdr(6, "AI agents & bots")
            for (aAny in agents) {
                val a = asMap(aAny)
                L.add("### `${pyStr(a["key"])}` — ${orE(a["name"])} (${pyStr(a["type"])}) — `${pyStr(a["file"])}`")
                L.add(
                    "- model: ${pyStr(a["aiVendor"])}/${pyStr(a["modelName"])} (temp ${pyStr(a["temperature"])}), " +
                        "apiEndpoint=${pyStr(a["enableApiEndpoint"])}"
                )
                if (truthy(a["knowledgeBase"])) L.add("- 📚 knowledgeBase → `${pyStr(a["knowledgeBase"])}`")
                for (tAny in asList(a["tools"])) {
                    val t = asMap(tAny)
                    L.add("- 🛠️ tool (${pyStr(t["type"])}) → `${pyStr(t["key"])}`")
                }
                for (opAny in asList(a["operations"])) {
                    val op = asMap(opAny)
                    L.add("- op `${pyStr(op["key"])}`: ${pyStr(orAny(op["systemMessage"], op["userMessage"], ""))}")
                }
                L.add("")
            }
        }

        // Integration
        hdr(7, "Integration: Services, Channels, Events & REST")
        val services = asList(result["services"])
        if (services.isNotEmpty()) {
            L.add("### Service models (.service)")
            for (svAny in services) {
                val sv = asMap(svAny)
                val attrs = Fmt.fields(
                    "base" to Fmt.codeList(sv["baseUrl"]),
                    "auth" to Fmt.list(sv["auth"]),
                    "table" to Fmt.codeList(sv["tableName"]),
                )
                L.add(
                    "- **${pyStr(sv["name"])}** (`${pyStr(sv["key"])}`, ${pyStr(sv["type"])})" +
                        (if (attrs.isEmpty()) "" else " · $attrs") + " — `${pyStr(sv["file"])}`"
                )
                for (opAny in asList(sv["operations"])) {
                    val op = asMap(opAny)
                    // in/out parameters are the operation's contract: without them a caller cannot be
                    // written, and they only ever appeared in the explorer.
                    val contract = Fmt.fields(
                        "in" to Fmt.codeList(asList(op["params"]).map { paramName(it) }.filter { it.isNotEmpty() }),
                        "out" to Fmt.codeList(asList(op["outParams"]).map { paramName(it) }.filter { it.isNotEmpty() }),
                    )
                    L.add(
                        "    - `${pyStr(op["method"])}` ${pyStr(orAny(op["fullUrl"], op["url"]))} " +
                            "(op `${pyStr(op["key"])}`)" + (if (contract.isEmpty()) "" else " · $contract")
                    )
                }
            }
            L.add("")
        }
        renderDataLayer(result, L)
        val channels = asList(result["channels"])
        if (channels.isNotEmpty()) {
            L.add("### Channels (.channel)")
            for (chAny in channels) {
                val ch = asMap(chAny)
                val attrs = Fmt.fields(
                    "topics" to Fmt.codeList(ch["topics"]),
                    "destination" to Fmt.codeList(ch["destination"]),
                )
                L.add(
                    "- `${pyStr(ch["key"])}` ${pyStr(ch["channelType"])}/${pyStr(ch["type"])}" +
                        (if (attrs.isEmpty()) "" else " · $attrs") + " — `${pyStr(ch["file"])}`"
                )
            }
            L.add("")
        }
        val eventsList = asList(result["events"])
        if (eventsList.isNotEmpty()) {
            L.add("### Events (.event)")
            for (evAny in eventsList) {
                val ev = asMap(evAny)
                val attrs = Fmt.fields(
                    "payload" to Fmt.codeList(ev["payload"]),
                    "correlation" to Fmt.codeList(ev["correlation"]),
                )
                L.add("- `${pyStr(ev["key"])}`" + (if (attrs.isEmpty()) "" else " — $attrs"))
            }
            L.add("")
        }
        val restCalls = asList(result["restCalls"])
        if (restCalls.isNotEmpty()) {
            L.add("### REST endpoints CALLED by the app (→ matched code)")
            for (rcAny in restCalls) {
                val rc = asMap(rcAny)
                val src = if (truthy(rc["where"])) "${pyStr(rc["source"])}/${pyStr(rc["where"])}" else pyStr(rc["source"])
                L.add("- `${pyStr(rc["method"])}` ${pyStr(rc["url"])}  _(from ${pyStr(rc["kind"])} `$src`)_")
                val matches = asList(rc["matches"])
                for (m in matches) L.add("    - ✅ served by ${pyStr(m)}")
                // `≈` for a loose path match, the same "uncertain" marker the explorer uses: it shares a
                // path segment with the call but is not a confident hit, so it must not read as "served by".
                for (m in asList(rc["looseMatches"])) L.add("    - ≈ possibly ${pyStr(m)}")
                if (matches.isEmpty())
                    L.add("    - ⚠️ no matching controller in project (external or unimplemented)")
            }
            L.add("")
        }

        // Java glue
        hdr(8, "Java glue code")
        val javaGlue = asList(result["javaGlue"])
        if (javaGlue.isNotEmpty()) {
            L.add("### Delegates / listeners (model-referenced classes)")
            for (jcAny in javaGlue) {
                val jc = asMap(jcAny)
                val inter = (asList(jc["interfaces"]).mapNotNull { it as? String }.toSet() intersect GLUE_INTERFACES).sorted()
                L.add("- `${pyStr(jc["fqn"])}` implements ${pyStr(inter)} — `${pyStr(jc["file"])}:${pyStr(jc["line"])}`")
            }
            L.add("")
        }
        val javaControllers = asList(result["javaControllers"])
        if (javaControllers.isNotEmpty()) {
            L.add("### REST controllers & endpoints")
            for (jcAny in javaControllers) {
                val jc = asMap(jcAny)
                L.add("- **${pyStr(jc["primary"])}** — `${pyStr(jc["file"])}`")
                for (epAny in asList(jc["endpoints"])) {
                    val ep = asMap(epAny)
                    L.add("    - `${pyStr(ep["http"])}` ${pyStr(ep["path"])} → ${pyStr(ep["handler"])}() (line ${pyStr(ep["line"])})")
                }
            }
            L.add("")
        }

        // Model <-> code resolved references
        hdr(9, "Resolved references (model → code / model)")
        val resolvedRefs = asList(result["resolvedRefs"]).map { asMap(it) }
        val codeRefs = resolvedRefs.filter { it["targetType"] == "bean" || it["targetType"] == "class" }
        val modelRefs = resolvedRefs.filter { it["targetType"] == "model" }
        // Both lists are per-reference, so they grow with the project (478 lines on a real one) while
        // saying the same kind of thing over and over. Capped, with the full set a query away.
        if (codeRefs.isNotEmpty()) {
            L.add("### Model → Java code")
            for (r in codeRefs.take(RESOLVED_REFS_LISTED)) {
                L.add("- `${pyStr(r["from"])}` [${pyStr(r["rel"])}] `${pyStr(r["value"])}` → ${pyStr(r["target"])}")
            }
            if (codeRefs.size > RESOLVED_REFS_LISTED) {
                L.add("- … (+${codeRefs.size - RESOLVED_REFS_LISTED} more — `resolvedRefs` in " +
                    "`$an.graph.json`)")
            }
            L.add("")
        }
        if (modelRefs.isNotEmpty()) {
            L.add("### Model → Model")
            for (r in modelRefs.take(RESOLVED_REFS_LISTED)) {
                L.add("- `${pyStr(r["from"])}` —${pyStr(r["rel"])}→ ${pyStr(r["kind"])} `${pyStr(r["value"])}` (`${pyStr(r["target"])}`)")
            }
            if (modelRefs.size > RESOLVED_REFS_LISTED) {
                L.add("- … (+${modelRefs.size - RESOLVED_REFS_LISTED} more — `resolvedRefs` in " +
                    "`$an.graph.json`)")
            }
            L.add("")
        }

        // Unresolved
        hdr(10, "Unresolved references (external / library / missing)")
        val unresolvedRefs = asList(result["unresolvedRefs"]).map { asMap(it) }
        val groups = LinkedHashMap<Pair<String, String>, MutableList<Map<String, Any?>>>()
        for (r in unresolvedRefs) {
            groups.getOrPut(Pair(pyStr(r["kind"]), pyStr(r["value"]))) { mutableListOf() }.add(r)
        }
        val platform = groups.filterKeys { it.first == "bean" && it.second in FLOWABLE_PLATFORM_BEANS }
        val othersG = groups.filterKeys { it !in platform.keys }
        val tupleCmp = compareBy<Map.Entry<Pair<String, String>, *>>({ it.key.first }, { it.key.second })
        if (platform.isNotEmpty()) {
            L.add("### Expected Flowable platform beans (provided by the engine, not project code)")
            for ((k, rs) in platform.entries.sortedWith(tupleCmp)) {
                val n = rs.map { pyStr(it["from"]) }.toSet().size
                L.add("- `${k.second}` — referenced by $n model(s)")
            }
            L.add("")
        }
        if (othersG.isNotEmpty()) {
            L.add("### Other unresolved — review (external dependency, typo, or missing)")
            for ((k, rs) in othersG.entries.sortedWith(tupleCmp)) {
                val froms = rs.map { pyStr(it["from"]) }.toSortedSet().toList()
                val more = if (froms.size > 1) " (+${froms.size - 1} more)" else ""
                L.add("- [${k.first}] `${k.second}` — from `${froms[0]}`$more")
            }
            L.add("")
        }
        if (unresolvedRefs.isEmpty()) {
            L.add("_None — every reference resolved within the project._\n")
        }

        // Uncertain links — suspect (loose/cross-type) resolutions and dynamic (expression-valued)
        // references; both are rendered dashed in the explorer and deserve a review pass.
        val suspectRefs = asList(result["resolvedRefs"]).map { asMap(it) }.filter { it["suspect"] == true }
        if (suspectRefs.isNotEmpty()) {
            L.add("### Suspect links — resolved via a loose or cross-type match (verify)")
            for (r in suspectRefs) {
                val fb = r["fallbackType"]?.let { " — actually a `${pyStr(it)}` model" } ?: ""
                L.add("- `${pyStr(r["from"])}` —${pyStr(r["rel"])}→ ${pyStr(r["kind"])} `${pyStr(r["value"])}`$fb")
            }
            L.add("")
        }
        val dynRefs = asList(result["dynamicRefs"]).map { asMap(it) }
        if (dynRefs.isNotEmpty()) {
            L.add("### Dynamic references (expression-valued — resolved at runtime)")
            for (r in dynRefs.take(30)) {
                val res = r["resolvedValue"]?.let { " → resolves to `${pyStr(it)}` (constant)" } ?: ""
                L.add("- `${pyStr(r["from"])}` —${pyStr(r["rel"])}→ ${pyStr(r["kind"])} `${pyStr(r["value"])}`$res")
            }
            if (dynRefs.size > 30) L.add("- … ${dynRefs.size - 30} more")
            L.add("")
        }

        // Access & user groups
        hdr(11, "Access & user groups (who can do what)")
        val acc = asList(result["access"]).map { asMap(it) }
        val groupsAll = asList(result["groups"])
        if (groupsAll.isNotEmpty()) {
            L.add(
                "**All groups/roles referenced (${groupsAll.size}):** " +
                    groupsAll.joinToString(", ") { "`${pyStr(it)}`" } + "\n"
            )
        }
        val appAcc = acc.filter { it["scope"] == "app" || it["scope"] == "page" }
        if (appAcc.isNotEmpty()) {
            L.add("### App / page access")
            for (a in appAcc) {
                val who0 = asList(a["groups"]).map { pyStr(it) } + asList(a["users"]).map { "user:${pyStr(it)}" }
                val who = if (who0.isNotEmpty()) who0.joinToString(", ") else "(everyone)"
                L.add("- ${pyStr(a["modelType"])} `${pyStr(a["model"])}`: $who")
            }
            L.add("")
        }
        val starts = acc.filter { it["action"] == "start" }
        if (starts.isNotEmpty()) {
            L.add("### Who can start (processes & cases)")
            for (a in starts.sortedBy { pyStr(it["model"]) }) {
                val who0 = asList(a["groups"]).map { pyStr(it) } + asList(a["users"]).map { pyStr(it) }
                val who = if (who0.isNotEmpty()) who0.joinToString(", ") else "(no restriction)"
                L.add("- ${pyStr(a["modelType"])} `${pyStr(a["model"])}` ← $who")
            }
            L.add("")
        }
        val assigns = acc.filter { it["action"] == "assign" }
        if (assigns.isNotEmpty()) {
            L.add("### Task assignment (candidate groups / assignees per model)")
            val bym = LinkedHashMap<String, MutableSet<String>>()
            for (a in assigns) {
                val set = bym.getOrPut(pyStr(a["model"])) { mutableSetOf() }
                set.addAll(asList(a["groups"]).map { pyStr(it) })
                set.addAll(asList(a["users"]).map { pyStr(it) })
            }
            for (model in bym.keys.sorted()) {
                L.add("- `$model`: ${bym[model]!!.sorted().joinToString(", ")}")
            }
            L.add("")
        }
        val doAcc = acc.filter { it["modelType"] == "dataObject" }
        if (doAcc.isNotEmpty()) {
            L.add("### Data object access (who may query/create/update/delete)")
            val bym = LinkedHashMap<String, MutableList<Map<String, Any?>>>()
            for (a in doAcc) bym.getOrPut(pyStr(a["model"])) { mutableListOf() }.add(a)
            for (model in bym.keys.sorted()) {
                val perms = bym[model]!!.joinToString("; ") { a ->
                    val g = asList(a["groups"]).joinToString("/") { pyStr(it) }
                    "${pyStr(a["action"])}=${if (g.isNotEmpty()) g else "?"}"
                }
                L.add("- `$model`: $perms")
            }
            L.add("")
        }
        val policies = asList(result["policies"]).map { asMap(it) }
        if (policies.isNotEmpty()) {
            L.add("### Security policies")
            for (p in policies) {
                L.add("- `${pyStr(p["key"])}` — `${pyStr(p["file"])}`")
                for (permAny in asList(p["permissions"])) {
                    val perm = asMap(permAny)
                    val roles = asList(perm["roles"]).map { pyStr(it) }
                    L.add("    - ${pyStr(perm["key"])}: ${if (roles.isNotEmpty()) roles.joinToString(", ") else "(none)"}")
                }
            }
            L.add("")
        }
        if (acc.isEmpty() && policies.isEmpty()) {
            L.add("_No explicit access restrictions found._\n")
        }

        // Code map
        hdr(12, "Code map (where things live)")
        if (agents.isNotEmpty()) {
            L.add("**Agents / bots (models):**")
            for (aAny in agents) {
                val a = asMap(aAny)
                L.add("- `${pyStr(a["key"])}` — `${pyStr(a["file"])}`")
            }
        }
        if (services.isNotEmpty()) {
            L.add("**Service models (.service):**")
            for (svAny in services) {
                val sv = asMap(svAny)
                val attrs = Fmt.fields(
                    "base" to Fmt.codeList(sv["baseUrl"]),
                    "table" to Fmt.codeList(sv["tableName"]),
                )
                L.add(
                    "- `${pyStr(sv["key"])}` (${pyStr(sv["type"])})" +
                        (if (attrs.isEmpty()) "" else " · $attrs") + " — `${pyStr(sv["file"])}`"
                )
            }
        }
        // Models grouped by folder
        val folders = LinkedHashMap<String, LinkedHashMap<String, Int>>()
        val bucketLabel = listOf(
            "processes" to "bpmn", "cases" to "cmmn", "decisions" to "dmn",
            "forms" to "form", "dataObjects" to "data", "services" to "service",
            "agents" to "agent", "channels" to "channel", "events" to "event",
            "dictionaries" to "dict", "policies" to "policy", "actions" to "action",
            "liquibase" to "liquibase", "others" to "other",
        )
        for ((bucket, label) in bucketLabel) {
            for (oAny in asList(result[bucket])) {
                val o = asMap(oAny)
                val fpath = (o["file"] as? String) ?: ""
                val head = fpath.split("!")[0]
                val folder = if (head.contains("/")) head.substringBeforeLast("/") else "."
                val fm = folders.getOrPut(folder) { LinkedHashMap() }
                fm[label] = (fm[label] ?: 0) + 1
            }
        }
        if (folders.isNotEmpty()) {
            L.add("\n**Models by folder:**")
            for (folder in folders.keys.sorted()) {
                val counts = folders[folder]!!.entries
                    .sortedWith(compareBy({ it.key }, { it.value }))
                    .joinToString(", ") { "${it.value} ${it.key}" }
                L.add("- `$folder/` — $counts")
            }
        }
        // Java by role
        val jbr = asMap(result["javaByRole"])
        if (jbr.isNotEmpty()) {
            L.add("\n**Java code by role:**")
            for (role in listOf(
                "controller", "delegate", "listener", "service", "repository",
                "configuration", "component", "other",
            )) {
                val items = asList(jbr[role])
                if (items.isEmpty()) continue
                if (role == "other") {
                    L.add("\n_other (no Spring/Flowable role — DTOs, utils, …): ${items.size} classes_")
                    continue
                }
                L.add("\n_$role (${items.size}):_")
                for (jc in items.map { asMap(it) }.sortedBy { pyStr(it["fqn"]) }.take(80)) {
                    var iface = ""
                    if (role == "delegate" || role == "listener") {
                        val rel = asList(jc["interfaces"]).mapNotNull { it as? String }
                            .filter { it.endsWith("Listener") || it in GLUE_INTERFACES }.sorted()
                        iface = if (rel.isNotEmpty()) " [${rel.joinToString(", ")}]" else ""
                    }
                    L.add("- `${pyStr(jc["fqn"])}`$iface — `${pyStr(jc["file"])}:${pyStr(jc["line"])}`")
                }
                if (items.size > 80) L.add("- … (+${items.size - 80} more)")
            }
        }
        L.add("")

        // Variables / expressions
        hdr(13, "Variables, beans & expressions")
        renderVariables(result, L)
        val beans = asList(result["beans"])
        if (beans.isNotEmpty()) {
            L.add("**Beans/objects with method calls:** " + beans.joinToString(", ") { "`${pyStr(it)}`" } + "\n")
        }
        val delegateClasses = asList(result["delegateClasses"])
        if (delegateClasses.isNotEmpty()) {
            L.add(
                "**JavaDelegate/listener classes referenced:** " +
                    delegateClasses.joinToString(", ") { "`${pyStr(it)}`" } + "\n"
            )
        }
        renderExpressions(result, L, an)

        // Node types this report does not have a section for. Several of them are the answer to a common
        // question — `serviceOperation.usedBy` is "who calls this operation", `method` is "which Java
        // method does this expression reach", the correlation types are "who throws this signal" — and
        // saying nothing about them left a reader assuming the report was the whole graph.
        val counts = LinkedHashMap<String, Int>()
        for (nAny in asList(asMap(result["graph"])["nodes"])) {
            val t = asMap(nAny)["type"]?.toString() ?: continue
            if (t in REPORTED_NODE_TYPES) continue
            counts[t] = (counts[t] ?: 0) + 1
        }
        if (counts.isNotEmpty()) {
            L.add("**Also in the graph** (queryable in `$an.graph.json`, no section here): " +
                counts.entries.sortedByDescending { it.value }.joinToString(" · ") { "${it.value} ${it.key}" } +
                ".\n")
        }

        // Findings — what is probably wrong, itemized. Computed in `Findings.kt`; before that these
        // checks lived only in the explorer's JavaScript, so no text artifact could state any of them.
        val findings = asList(result["findings"]).map { asMap(it) }
        val checks = asMap(result["checks"])
        if (findings.isNotEmpty()) {
            val open = (checks["open"] as? Number)?.toInt() ?: findings.size
            hdr(14, "Findings — $open open")
            L.add(checks.entries.filter { it.key != "open" }
                .joinToString(" · ") { "${SummaryRenderer.CHECK_LABELS[it.key] ?: it.key}: ${it.value}" })
            L.add("")
            for ((check, group) in findings.groupBy { it["check"]?.toString() ?: "?" }) {
                L.add("**${SummaryRenderer.CHECK_LABELS[check] ?: check}** (${group.size})")
                for (f in group.take(FINDINGS_PER_CHECK)) {
                    val mark = if (f["severity"] == "error") "⚠" else "·"
                    // A parse finding's label *is* its file — don't print the same path twice.
                    val fileText = f["file"]?.toString()?.takeIf { it != f["label"]?.toString() }
                        ?.let { if (truthy(f["line"])) "$it:${pyStr(f["line"])}" else it }
                    val where = Fmt.fields(
                        "in" to Fmt.codeList(f["label"]),
                        "at" to Fmt.codeList(f["element"]),
                        "file" to Fmt.codeList(fileText),
                    )
                    L.add("- $mark ${pyStr(f["message"])}" + (if (where.isEmpty()) "" else " — $where"))
                    if (truthy(f["snippet"])) L.add("    `${pyStr(f["snippet"])}`")
                }
                if (group.size > FINDINGS_PER_CHECK) {
                    L.add("- … (+${group.size - FINDINGS_PER_CHECK} more — see `findings` in " +
                        "`$an.graph.json`)")
                }
                L.add("")
            }
        }

        // (There used to be a §14 "Warnings" section here listing `result.warnings`. Those are the same
        // parse/read failures the findings above now report as `unparseable files`, with their file and
        // message — so the section only repeated itself. `warnings`/`diagnostics` remain in graph.json.)
        return L.joinToString("\n")
    }

    /** Port of `_render_stage(node, L, depth)`. */
    /** The per-element-type lists of a parsed process; anything an element can carry lives in one of them. */
    private val ELEMENT_BUCKETS = listOf(
        "userTasks", "serviceTasks", "scriptTasks", "ruleTasks", "callActivities",
        "subProcesses", "events", "gateways", "otherTasks",
    )

    /**
     * The data layer as one chain: **service ↔ Liquibase table ↔ data object**, column by column.
     *
     * `LiquibaseCoverage` replays the changelogs, matches every column against the service mapping and
     * the data objects that consume it, and records changelog authority (live / superseded / orphan). It
     * is the most expensive analysis in `:core` — and its result reached only the HTML explorer's schema
     * tab. A report that lists a service, a data object and a changelog separately leaves the reader to
     * work out whether they actually line up, which is the one thing the analysis already knows.
     *
     * Only the rows that do *not* line up are listed: `ok` rows are covered by the count, while a gap is
     * the thing worth a line.
     */
    @Suppress("UNCHECKED_CAST")
    private fun renderDataLayer(result: Map<String, Any?>, L: MutableList<String>) {
        val services = asList(result["services"]).map { asMap(it) }
            .filter { truthy(asMap(it["schemaCoverage"])) }
        val changelogs = asList(result["liquibase"]).map { asMap(it) }
        if (services.isEmpty() && changelogs.none { truthy(asMap(it["authority"])["status"]) }) return

        L.add("### Data layer — service ↔ Liquibase table ↔ data object")
        for (sv in services) {
            val cov = asMap(sv["schemaCoverage"])
            val counts = asMap(cov["counts"])
            val ok = (counts["ok"] as? Number)?.toInt() ?: 0
            val total = (counts["total"] as? Number)?.toInt() ?: 0
            L.add(
                "- **${pyStr(orAny(sv["name"], sv["key"]))}** (`${pyStr(sv["key"])}`) → " +
                    Fmt.join(
                        "table ${Fmt.codeList(cov["table"])}",
                        if (truthy(cov["liquibase"])) "· changelog ${Fmt.codeList(cov["liquibase"])}" else "",
                        "· $ok/$total columns mapped end-to-end",
                        if (truthy(cov["dataObjects"])) "· data objects ${Fmt.codeList(cov["dataObjects"])}" else "",
                    )
            )
            val gaps = (cov["rows"] as? List<Map<String, Any?>> ?: emptyList())
                .filter { it["status"] != "ok" }
            for (r in gaps.take(SCHEMA_ROWS_LISTED)) {
                val what = when (r["status"]) {
                    "no-service" -> "in Liquibase only — the service does not map it"
                    "no-dataobject" -> "mapped by the service but no data object uses it"
                    "extra-service" -> "mapped by the service but not in any changelog"
                    else -> pyStr(r["status"])
                }
                val sqlType = Fmt.list(r["sqlType"]).let { if (it.isEmpty()) "" else " ($it)" }
                L.add("    - ⚠ ${Fmt.codeList(r["sql"])}$sqlType — $what")
            }
            if (gaps.size > SCHEMA_ROWS_LISTED) {
                L.add("    - … (+${gaps.size - SCHEMA_ROWS_LISTED} more gap(s))")
            }
        }
        // Changelogs whose authority is in doubt: an orphan nobody references, or one a later changelog
        // has superseded. Deploying against the wrong one is a silent schema drift.
        for (cl in changelogs) {
            val auth = asMap(cl["authority"])
            val status = auth["status"]?.toString() ?: continue
            if (status == "live") continue
            val detail = when (status) {
                "superseded" -> "superseded by ${Fmt.codeList(auth["supersededBy"])}"
                "orphan" -> "referenced by no service or data object"
                else -> status
            }
            L.add("- ⚠ changelog `${pyStr(cl["key"])}` — $detail — `${pyStr(cl["file"])}`")
        }
        L.add("")
    }

    /**
     * Variables **with their provenance**: which scopes they live in, where they are set and where read.
     *
     * This section used to print `result.variables` — a flat list of names, and a narrow one: on the test
     * fixture it named 4 of the project's 17 variables, and included `notifierBean` (a bean, not a
     * variable). Meanwhile every `variable` node already carried `scopes`, `usages` with snippets,
     * `ioParams` (the in/out mappings that carry it between models) and `scriptSites` (the scripts that
     * touch it) — the facts you need before writing an expression or a delegate. None of it was rendered.
     *
     * `heuristic` variables are marked: those names come from parsing a script, not from a declaration,
     * so they may be a local, a typo or a misread.
     */
    @Suppress("UNCHECKED_CAST")
    private fun renderVariables(result: Map<String, Any?>, L: MutableList<String>) {
        val nodes = (asMap(result["graph"])["nodes"] as? List<Map<String, Any?>>)?.filter {
            it["type"] == "variable"
        } ?: emptyList()
        if (nodes.isEmpty()) {
            // Nothing in the graph (e.g. a bucket-only result): fall back to the flat name list.
            val names = asList(result["variables"])
            if (names.isNotEmpty()) L.add("**Variables:** " + Fmt.codeList(names) + "\n")
            return
        }
        L.add("**Variables (${nodes.size})** — where each one lives, is set and is read:\n")
        val shown = nodes.sortedBy { it["key"]?.toString() ?: "" }.take(VARIABLES_LISTED)
        for (n in shown) {
            val d = asMap(n["data"])
            val scopes = Fmt.list(d["scopes"])
            // `in on \`callSub\`: orderId→subOrderId`, or just the target when a mapping has no source
            // (a literal or expression feeding a bot input) — never `None→customerEmail`.
            val params = (d["ioParams"] as? List<Map<String, Any?>> ?: emptyList()).map {
                val src = Fmt.list(it["source"])
                val tgt = Fmt.list(it["target"])
                val mapping = when {
                    src.isNotEmpty() && tgt.isNotEmpty() && src != tgt -> ": $src→$tgt"
                    tgt.isNotEmpty() -> ": $tgt"
                    else -> ""
                }
                Fmt.join("${pyStr(it["dir"])} on", Fmt.codeList(it["element"])) + mapping
            }.distinct()
            // Only sites we can name — an action's bot script has no element of its own.
            val scripts = (d["scriptSites"] as? List<Map<String, Any?>> ?: emptyList())
                .mapNotNull { s ->
                    val name = orAny(s["elementName"], s["element"], "")
                    if (truthy(name)) "`${pyStr(name)}`" else null
                }.distinct()
            // "(in|out parameter on X) a → b" / "(script ≈ read · Stamp order)" / "(form field)" — the
            // harvesters already phrase where a variable came from, so keep their words; but drop the
            // ones the structured `passed as` / `touched by scripts` fields below already state, or every
            // variable says the same thing twice.
            val where = (d["usages"] as? List<Map<String, Any?>> ?: emptyList())
                .flatMap { u ->
                    val model = u["model"]?.toString()?.substringAfter(':') ?: ""
                    asList(u["snippets"]).map { s -> "$model ${pyStr(s)}" }
                }
                .filterNot { params.isNotEmpty() && it.contains("parameter on") }
                .filterNot { scripts.isNotEmpty() && it.contains("(script") }
            val head = Fmt.join(
                "- `${pyStr(n["key"])}`",
                if (scopes.isNotEmpty()) "[$scopes]" else "",
                if (d["heuristic"] == true) "⚠ _inferred from a script_" else "",
            )
            L.add(head)
            val detail = Fmt.fields(
                "used in" to Fmt.cap(where, 4),
                "passed as" to Fmt.cap(params, 3),
                "touched by scripts" to Fmt.cap(scripts, 3),
            )
            if (detail.isNotEmpty()) L.add("    - $detail")
        }
        if (nodes.size > VARIABLES_LISTED) {
            L.add("- … (+${nodes.size - VARIABLES_LISTED} more — every variable is a node in the graph)")
        }
        L.add("")
    }

    /**
     * Expressions grouped by the bean or function they call, with their problems marked.
     *
     * This used to be a `<details>` dump of every expression string in the project — 492 lines / 23 KB on
     * a real project, alphabetically sorted, with no indication that some of them do not parse. Collapsing
     * the block hides it from a human but costs an LLM the same tokens either way. Grouping by callee
     * answers the question the list was there for ("what does this bean get used for") and marking the
     * broken ones stops a reader copying an expression Atlas already knows is invalid.
     */
    @Suppress("UNCHECKED_CAST")
    private fun renderExpressions(result: Map<String, Any?>, L: MutableList<String>, an: String) {
        val nodes = (asMap(result["graph"])["nodes"] as? List<Map<String, Any?>>)?.filter {
            it["type"] == "expression" || it["type"] == "binding"
        } ?: emptyList()
        if (nodes.isEmpty()) {
            val expressions = asList(result["expressions"])
            if (expressions.isNotEmpty()) L.add("**Expressions:** " + Fmt.cap(expressions.map {
                "`${pyStr(it)}`"
            }, 30) + "\n")
            return
        }
        // The leading `${`/`{{` and the first identifier are what group an expression: `${myBean.x()}`
        // and `${myBean.y()}` belong together under `myBean`.
        val groups = LinkedHashMap<String, MutableList<Map<String, Any?>>>()
        for (n in nodes) {
            val text = n["key"]?.toString() ?: continue
            val inner = text.removePrefix("\${").removePrefix("#{").removePrefix("{{").trimStart()
            val head = Regex("^[A-Za-z_$][A-Za-z0-9_$]*(?::[A-Za-z0-9_$]+)?").find(inner)?.value
            groups.getOrPut(head?.ifEmpty { null } ?: "(other)") { ArrayList() }.add(n)
        }
        L.add("**Expressions (${nodes.size})** — grouped by what they call:\n")
        val ordered = groups.entries.sortedWith(compareByDescending<Map.Entry<String, MutableList<Map<String, Any?>>>> {
            it.value.size
        }.thenBy { it.key })
        for ((head, exprs) in ordered.take(EXPRESSION_GROUPS)) {
            val broken = exprs.count { e ->
                (asMap(e["data"])["problems"] as? List<Map<String, Any?>>)?.any { it["severity"] == "error" } == true
            }
            val suspect = exprs.count { e ->
                val p = asMap(e["data"])["problems"] as? List<Map<String, Any?>> ?: emptyList()
                p.isNotEmpty() && p.none { it["severity"] == "error" }
            }
            val flags = Fmt.fields("invalid" to (if (broken > 0) "$broken ⚠" else ""),
                "suspect" to (if (suspect > 0) "$suspect" else ""))
            L.add("- `$head` (${exprs.size})" + (if (flags.isEmpty()) "" else " — $flags"))
            for (e in exprs.take(EXPRESSIONS_PER_GROUP)) {
                val problems = asMap(e["data"])["problems"] as? List<Map<String, Any?>> ?: emptyList()
                val mark = when {
                    problems.any { it["severity"] == "error" } -> " ⚠ "
                    problems.isNotEmpty() -> " ? "
                    else -> " "
                }
                val users = Fmt.cap(asList(asMap(e["data"])["usedBy"]).map {
                    "`${pyStr(it).substringAfter(':')}`"
                }, 3)
                L.add("    -$mark`${pyStr(e["key"])}`" + (if (users.isEmpty()) "" else " — in $users"))
            }
            if (exprs.size > EXPRESSIONS_PER_GROUP) {
                L.add("    - … (+${exprs.size - EXPRESSIONS_PER_GROUP} more)")
            }
        }
        if (groups.size > EXPRESSION_GROUPS) {
            L.add("- … (+${groups.size - EXPRESSION_GROUPS} more callees — every expression is a node in " +
                "`$an.graph.json`)")
        }
        L.add("")
    }

    /**
     * The plan-model tree, with each plan item's **entry/exit criteria resolved to their sentry's
     * condition**.
     *
     * A CMMN case has no sequence flows: what makes a plan item start or stop is its criteria, and the
     * condition behind one lives in a separate `sentries` list keyed by `sentryRef`. Listing the two
     * apart (plan items here, sentries there) left the reader to join them by id — so the report showed
     * a case's structure while withholding what actually drives it. [sentries] is that index.
     */
    private fun renderStage(
        node: Map<String, Any?>,
        L: MutableList<String>,
        depth: Int,
        sentries: Map<String, Map<String, Any?>> = emptyMap(),
        titleSuffix: String = "",
    ) {
        val ind = "    ".repeat(depth)
        L.add("$ind- 📁 **${DesignTerms.label("el", node["type"])}** " +
            "${pyStr(orAny(node["name"], node["id"], ""))}$titleSuffix")
        // criteria of *this* stage's plan items, keyed by the definition the plan item refers to
        val critByItem = LinkedHashMap<String, MutableList<Map<String, Any?>>>()
        for (cAny in asList(node["criteria"])) {
            val c = asMap(cAny)
            val item = c["planItemDef"]?.toString()?.ifEmpty { null } ?: continue
            critByItem.getOrPut(item) { ArrayList() }.add(c)
        }
        fun criteriaSuffix(ch: Map<String, Any?>): String {
            val id = ch["id"]?.toString() ?: return ""
            val crits = critByItem[id] ?: return ""
            val parts = crits.map { c ->
                val gate = if (c["type"] == "exitCriterion") "exit" else "entry"
                val sen = sentries[c["sentryRef"]?.toString()] ?: emptyMap()
                val on = Fmt.list(sen["onParts"])
                when {
                    truthy(sen["condition"]) -> "$gate if `${pyStr(sen["condition"])}`"
                    on.isNotEmpty() -> "$gate on $on"
                    else -> gate
                }
            }
            return " · " + parts.joinToString(" · ")
        }
        for (chAny in asList(node["children"])) {
            val ch = asMap(chAny)
            var rules = ""
            if (truthy(ch["rules"])) {
                rules = " " + asMap(ch["rules"]).entries.joinToString(", ") { "${pyStr(it.key)}=${pyStr(it.value)}" }
            }
            if (ch.containsKey("children")) {
                renderStage(ch, L, depth + 1, sentries, criteriaSuffix(ch))
            } else {
                var extra = ""
                for (k in listOf(
                    "assignee", "formKey", "processRef", "caseRef", "decisionRef",
                    "serviceModelKey", "agentModelKey", "dataObjectKey",
                )) {
                    if (truthy(ch[k])) extra += " $k=`${pyStr(ch[k])}`"
                }
                L.add("$ind    - ${DesignTerms.label("el", ch["type"])} " +
                    "${pyStr(orAny(ch["name"], ch["id"], ""))}$extra$rules${criteriaSuffix(ch)}")
            }
        }
    }

    // ---- Python str()/repr()/truthiness helpers -------------------------------------------------

    @Suppress("UNCHECKED_CAST")
    /**
     * Rank each element of a process by **execution order**: a topological sort over its sequence
     * flows, start events first, and parallel siblings in the order their flows are declared — so a
     * gateway's branches are listed in the same order the gateway's own `next:` line names them.
     *
     * A process is stored grouped by element type, so rendering it in storage order buries the start
     * event among the last lines and never says what follows what. Sorting by the flows instead means
     * every step appears after the steps that can reach it.
     *
     * Robustness matters more than elegance here — real exports contain loops, unreachable fragments and
     * flows pointing at elements that live in a sub-process. So: a cycle releases its
     * earliest-in-document member and carries on, and anything the flows never mention keeps its
     * document position rather than disappearing.
     */
    private fun flowOrder(p: Map<String, Any?>, docIds: List<String>): Map<String, Int> {
        val flows = asList(p["flows"]).map { asMap(it) }.mapNotNull { f ->
            val from = f["from"]?.toString()?.ifEmpty { null }
            val to = f["to"]?.toString()?.ifEmpty { null }
            if (from == null || to == null) null else from to to
        }
        val docPos = HashMap<String, Int>()
        docIds.forEachIndexed { i, id -> docPos.putIfAbsent(id, i) }
        // Start events lead, whatever bucket order put them in.
        val starts = asList(p["events"]).map { asMap(it) }
            .filter { it["type"] == "startEvent" }
            .mapNotNull { it["id"]?.toString()?.ifEmpty { null } }
            .toSet()
        fun pos(id: String): Int =
            (docPos[id] ?: Int.MAX_VALUE / 2) - (if (id in starts) docIds.size + 1 else 0)
        if (flows.isEmpty()) return docIds.associateWith { pos(it) }

        val nodes = LinkedHashSet<String>(docIds)
        for ((f, t) in flows) { nodes.add(f); nodes.add(t) }
        val outgoing = HashMap<String, MutableList<String>>()
        val indegree = HashMap<String, Int>()
        for (n in nodes) indegree[n] = 0
        for ((f, t) in flows) {
            outgoing.getOrPut(f) { ArrayList() }.add(t)
            indegree[t] = (indegree[t] ?: 0) + 1
        }
        // Discovery order: seeds by document position (start events lead), everything else in the order
        // the flows reach it. Ordering the frontier by discovery is what keeps a gateway's branches in
        // their declared order instead of in whatever order the buckets happened to store them.
        val discovered = HashMap<String, Int>()
        var seen = 0
        val ready = java.util.TreeSet<String>(compareBy({ discovered[it] ?: Int.MAX_VALUE }, { it }))
        val inFlow = HashSet<String>()
        for ((f, t) in flows) { inFlow.add(f); inFlow.add(t) }
        val seeds = nodes.filter { indegree[it] == 0 }.sortedWith(compareBy({ pos(it) }, { it }))
        for (seed in seeds.filter { it in inFlow }) {
            discovered[seed] = seen++
            ready.add(seed)
        }
        // Elements no flow mentions are also seeds, but they are not part of the walk — park them after
        // it, so a disconnected fragment cannot break the line a reader is following.
        var loose = nodes.size * 2
        for (seed in seeds.filter { it !in inFlow }) {
            discovered[seed] = loose++
            ready.add(seed)
        }
        val remaining = LinkedHashSet(nodes)
        val rank = HashMap<String, Int>()
        var n = 0
        while (remaining.isNotEmpty()) {
            // A cycle empties the frontier while nodes remain: release the earliest one and carry on.
            val next = ready.pollFirst() ?: remaining.minByOrNull { discovered[it] ?: pos(it) }!!
            if (!remaining.remove(next)) continue
            rank[next] = n++
            for (t in outgoing[next] ?: emptyList()) {
                discovered.putIfAbsent(t, seen++)
                indegree[t] = (indegree[t] ?: 1) - 1
                if ((indegree[t] ?: 0) <= 0 && t in remaining) ready.add(t)
            }
        }
        return rank
    }

    /**
     * `elementId → ["approveTask [${total > 100}]", …]` from the sequence flows — what each step hands
     * control to, with the condition or flow name that selects it. This replaced a separate list of
     * conditional flows at the end of each process, which stated the same fact further from the element
     * it belongs to and said nothing about the unconditional ones.
     */
    private fun successorsByElement(p: Map<String, Any?>): Map<String, List<String>> {
        val out = LinkedHashMap<String, MutableList<String>>()
        for (fAny in asList(p["flows"])) {
            val f = asMap(fAny)
            val from = f["from"]?.toString()?.ifEmpty { null } ?: continue
            val to = f["to"]?.toString()?.ifEmpty { null } ?: continue
            val label = when {
                truthy(f["condition"]) -> " [`${pyStr(f["condition"])}`]"
                truthy(f["name"]) -> " (${pyStr(f["name"])})"
                else -> ""
            }
            out.getOrPut(from) { ArrayList() }.add("`$to`$label")
        }
        return out
    }

    private fun asMap(v: Any?): Map<String, Any?> = (v as? Map<String, Any?>) ?: emptyMap()

    private fun asList(v: Any?): List<Any?> = (v as? List<Any?>) ?: emptyList()

    /** Python truthiness. */
    private fun truthy(v: Any?): Boolean = when (v) {
        null -> false
        is Boolean -> v
        is Number -> v.toDouble() != 0.0
        is String -> v.isNotEmpty()
        is Collection<*> -> v.isNotEmpty()
        is Map<*, *> -> v.isNotEmpty()
        else -> true
    }

    /** Python `a or b or …` — first truthy operand, else the last. */
    private fun orAny(vararg vals: Any?): Any? {
        for (v in vals) if (truthy(v)) return v
        return vals.last()
    }

    /** `v or ''` rendered through str(). */
    private fun orE(v: Any?): String = if (truthy(v)) pyStr(v) else ""

    /** Format a number the way a Python f-string does (integral values drop the trailing `.0`). */
    private fun numStr(n: Number): String = when (n) {
        is Double -> if (n.isFinite() && n == Math.floor(n)) n.toLong().toString() else n.toString()
        is Float -> { val d = n.toDouble(); if (d.isFinite() && d == Math.floor(d)) d.toLong().toString() else n.toString() }
        else -> n.toString()
    }

    /** Python `str(v)`. */
    private fun pyStr(v: Any?): String = when (v) {
        null -> "None"
        is Boolean -> if (v) "True" else "False"
        is Number -> numStr(v)
        is String -> v
        is List<*> -> pyRepr(v)
        is Map<*, *> -> pyRepr(v)
        else -> v.toString()
    }

    /** Python `repr(v)`. */
    private fun pyRepr(v: Any?): String = when (v) {
        null -> "None"
        is Boolean -> if (v) "True" else "False"
        is Number -> numStr(v)
        is String -> reprStr(v)
        is List<*> -> v.joinToString(", ", "[", "]") { pyRepr(it) }
        is Map<*, *> -> v.entries.joinToString(", ", "{", "}") { "${pyRepr(it.key)}: ${pyRepr(it.value)}" }
        else -> v.toString()
    }

    /** Python `repr(str)` — single quotes unless the string has a `'` but no `"`. */
    private fun reprStr(str: String): String {
        val quote = if (str.contains('\'') && !str.contains('"')) '"' else '\''
        val sb = StringBuilder()
        sb.append(quote)
        for (c in str) {
            when (c) {
                '\\' -> sb.append("\\\\")
                '\n' -> sb.append("\\n")
                '\r' -> sb.append("\\r")
                '\t' -> sb.append("\\t")
                quote -> sb.append('\\').append(quote)
                else -> sb.append(c)
            }
        }
        sb.append(quote)
        return sb.toString()
    }
}
